----------------------------------------
Timestamp: 24/02/2016 17:03:41
Message: <Exception handlingInstanceId="54b355f2-0332-4403-98b4-7be7dc439b6c">
  <Description>An exception of type 'System.Data.OracleClient.OracleException' occurred and was caught.</Description>
  <DateTime>2016-02-24 17:03:41Z</DateTime>
  <ExceptionType>System.Data.OracleClient.OracleException, System.Data.OracleClient, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</ExceptionType>
  <Message>ORA-20005: CONTEXTO DE ACESSO INVALIDO
ORA-06512: at "ERESULTS_V2_DEV.PCK_ER_DOCS", line 311
ORA-06512: at "ERESULTS_V2_DEV.PCK_ER_DOCS", line 2431
ORA-06512: at line 1
</Message>
  <Source>System.Data.OracleClient</Source>
  <HelpLink />
  <Property name="Code">20005</Property>
  <Property name="ErrorCode">-2146232008</Property>
  <Property name="Data">System.Collections.ListDictionaryInternal</Property>
  <Property name="TargetSite">Void CheckError(System.Data.OracleClient.OciErrorHandle, Int32)</Property>
  <Property name="HResult">-2146232008</Property>
  <StackTrace>   at System.Data.OracleClient.OracleConnection.CheckError(OciErrorHandle errorHandle, Int32 rc)
   at System.Data.OracleClient.OracleCommand.Execute(OciStatementHandle statementHandle, CommandBehavior behavior, Boolean needRowid, OciRowidDescriptor&amp; rowidDescriptor, ArrayList&amp; resultParameterOrdinals)
   at System.Data.OracleClient.OracleCommand.Execute(OciStatementHandle statementHandle, CommandBehavior behavior, ArrayList&amp; resultParameterOrdinals)
   at System.Data.OracleClient.OracleCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.OracleClient.OracleCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.DoExecuteReader(DbCommand command, CommandBehavior cmdBehavior)
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.ExecuteReader(DbCommand command)
   at Microsoft.Practices.EnterpriseLibrary.Data.Oracle.OracleDatabase.ExecuteReader(DbCommand command)
   at Cpchs.Eresults.Common.WCF.BusinessEntities.DocumentManagementBER.GetDocsDB(String companyDB, String documentRef, String documentExternalId, String entitiesIds, String episodeType, String episodeId, String patientId, String patientType, Nullable`1 episodeStartDate, Nullable`1 episodeEndDate, String institution, String place, String application, String documentType, Nullable`1 executionStartDate, Nullable`1 executionEndDate, Nullable`1 validationStartDate, Nullable`1 validationEndDate, Nullable`1 emissionStartDate, Nullable`1 emissionEndDate, String reqService, String execService, String globalFilters, String docsSession, String servsSession, String username, Nullable`1 pageNumber, Nullable`1 itemsPerPage, String orderField, String orderType, String report, String isPublic, Nullable`1 workspaceId, String filterString, String period, Nullable`1&amp; resultCount) in d:\eResults\16R101\Glintths.Er.WebServices\Data\Glintths.Er.Common.Data\BusinessEntities\Documents\Document\DocumentManagementBER.cs:line 597</StackTrace>
  <additionalInfo>
    <info name="MachineName" value="RPEREIRA" />
    <info name="TimeStamp" value="24/02/2016 17:03:41" />
    <info name="FullName" value="Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=4.1.0.0, Culture=neutral, PublicKeyToken=null" />
    <info name="AppDomainName" value="/LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-6-131008066966944141" />
    <info name="ThreadIdentity" value="" />
    <info name="WindowsIdentity" value="NT AUTHORITY\SYSTEM" />
  </additionalInfo>
</Exception>
Category: General
Priority: 0
EventId: 100
Severity: Error
Title:Enterprise Library Exception Handling
Machine: RPEREIRA
Application Domain: /LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-6-131008066966944141
Process Id: 26252
Process Name: C:\WINDOWS\SysWOW64\inetsrv\w3wp.exe
Win32 Thread Id: 26196
Thread Name: 
Extended Properties: 
----------------------------------------
----------------------------------------
Timestamp: 24/02/2016 17:03:52
Message: <Exception handlingInstanceId="cbfa0db8-2377-406a-948c-64e2e174ccfe">
  <Description>An exception of type 'System.Data.OracleClient.OracleException' occurred and was caught.</Description>
  <DateTime>2016-02-24 17:03:52Z</DateTime>
  <ExceptionType>System.Data.OracleClient.OracleException, System.Data.OracleClient, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</ExceptionType>
  <Message>ORA-20005: CONTEXTO DE ACESSO INVALIDO
ORA-06512: at "ERESULTS_V2_DEV.PCK_ER_DOCS", line 311
ORA-06512: at "ERESULTS_V2_DEV.PCK_ER_DOCS", line 2431
ORA-06512: at line 1
</Message>
  <Source>System.Data.OracleClient</Source>
  <HelpLink />
  <Property name="Code">20005</Property>
  <Property name="ErrorCode">-2146232008</Property>
  <Property name="Data">System.Collections.ListDictionaryInternal</Property>
  <Property name="TargetSite">Void CheckError(System.Data.OracleClient.OciErrorHandle, Int32)</Property>
  <Property name="HResult">-2146232008</Property>
  <StackTrace>   at System.Data.OracleClient.OracleConnection.CheckError(OciErrorHandle errorHandle, Int32 rc)
   at System.Data.OracleClient.OracleCommand.Execute(OciStatementHandle statementHandle, CommandBehavior behavior, Boolean needRowid, OciRowidDescriptor&amp; rowidDescriptor, ArrayList&amp; resultParameterOrdinals)
   at System.Data.OracleClient.OracleCommand.Execute(OciStatementHandle statementHandle, CommandBehavior behavior, ArrayList&amp; resultParameterOrdinals)
   at System.Data.OracleClient.OracleCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.OracleClient.OracleCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.DoExecuteReader(DbCommand command, CommandBehavior cmdBehavior)
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.ExecuteReader(DbCommand command)
   at Microsoft.Practices.EnterpriseLibrary.Data.Oracle.OracleDatabase.ExecuteReader(DbCommand command)
   at Cpchs.Eresults.Common.WCF.BusinessEntities.DocumentManagementBER.GetDocsDB(String companyDB, String documentRef, String documentExternalId, String entitiesIds, String episodeType, String episodeId, String patientId, String patientType, Nullable`1 episodeStartDate, Nullable`1 episodeEndDate, String institution, String place, String application, String documentType, Nullable`1 executionStartDate, Nullable`1 executionEndDate, Nullable`1 validationStartDate, Nullable`1 validationEndDate, Nullable`1 emissionStartDate, Nullable`1 emissionEndDate, String reqService, String execService, String globalFilters, String docsSession, String servsSession, String username, Nullable`1 pageNumber, Nullable`1 itemsPerPage, String orderField, String orderType, String report, String isPublic, Nullable`1 workspaceId, String filterString, String period, Nullable`1&amp; resultCount) in d:\eResults\16R101\Glintths.Er.WebServices\Data\Glintths.Er.Common.Data\BusinessEntities\Documents\Document\DocumentManagementBER.cs:line 597</StackTrace>
  <additionalInfo>
    <info name="MachineName" value="RPEREIRA" />
    <info name="TimeStamp" value="24/02/2016 17:03:52" />
    <info name="FullName" value="Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=4.1.0.0, Culture=neutral, PublicKeyToken=null" />
    <info name="AppDomainName" value="/LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-6-131008066966944141" />
    <info name="ThreadIdentity" value="" />
    <info name="WindowsIdentity" value="NT AUTHORITY\SYSTEM" />
  </additionalInfo>
</Exception>
Category: General
Priority: 0
EventId: 100
Severity: Error
Title:Enterprise Library Exception Handling
Machine: RPEREIRA
Application Domain: /LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-6-131008066966944141
Process Id: 26252
Process Name: C:\WINDOWS\SysWOW64\inetsrv\w3wp.exe
Win32 Thread Id: 21652
Thread Name: 
Extended Properties: 
----------------------------------------
----------------------------------------
Timestamp: 24/02/2016 17:04:06
Message: <Exception handlingInstanceId="698d9d83-6e33-405a-8186-e618e2cae51c">
  <Description>An exception of type 'System.Data.OracleClient.OracleException' occurred and was caught.</Description>
  <DateTime>2016-02-24 17:04:06Z</DateTime>
  <ExceptionType>System.Data.OracleClient.OracleException, System.Data.OracleClient, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</ExceptionType>
  <Message>ORA-20005: CONTEXTO DE ACESSO INVALIDO
ORA-06512: at "ERESULTS_V2_DEV.PCK_ER_DOCS", line 311
ORA-06512: at "ERESULTS_V2_DEV.PCK_ER_DOCS", line 2431
ORA-06512: at line 1
</Message>
  <Source>System.Data.OracleClient</Source>
  <HelpLink />
  <Property name="Code">20005</Property>
  <Property name="ErrorCode">-2146232008</Property>
  <Property name="Data">System.Collections.ListDictionaryInternal</Property>
  <Property name="TargetSite">Void CheckError(System.Data.OracleClient.OciErrorHandle, Int32)</Property>
  <Property name="HResult">-2146232008</Property>
  <StackTrace>   at System.Data.OracleClient.OracleConnection.CheckError(OciErrorHandle errorHandle, Int32 rc)
   at System.Data.OracleClient.OracleCommand.Execute(OciStatementHandle statementHandle, CommandBehavior behavior, Boolean needRowid, OciRowidDescriptor&amp; rowidDescriptor, ArrayList&amp; resultParameterOrdinals)
   at System.Data.OracleClient.OracleCommand.Execute(OciStatementHandle statementHandle, CommandBehavior behavior, ArrayList&amp; resultParameterOrdinals)
   at System.Data.OracleClient.OracleCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.OracleClient.OracleCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.DoExecuteReader(DbCommand command, CommandBehavior cmdBehavior)
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.ExecuteReader(DbCommand command)
   at Microsoft.Practices.EnterpriseLibrary.Data.Oracle.OracleDatabase.ExecuteReader(DbCommand command)
   at Cpchs.Eresults.Common.WCF.BusinessEntities.DocumentManagementBER.GetDocsDB(String companyDB, String documentRef, String documentExternalId, String entitiesIds, String episodeType, String episodeId, String patientId, String patientType, Nullable`1 episodeStartDate, Nullable`1 episodeEndDate, String institution, String place, String application, String documentType, Nullable`1 executionStartDate, Nullable`1 executionEndDate, Nullable`1 validationStartDate, Nullable`1 validationEndDate, Nullable`1 emissionStartDate, Nullable`1 emissionEndDate, String reqService, String execService, String globalFilters, String docsSession, String servsSession, String username, Nullable`1 pageNumber, Nullable`1 itemsPerPage, String orderField, String orderType, String report, String isPublic, Nullable`1 workspaceId, String filterString, String period, Nullable`1&amp; resultCount) in d:\eResults\16R101\Glintths.Er.WebServices\Data\Glintths.Er.Common.Data\BusinessEntities\Documents\Document\DocumentManagementBER.cs:line 597</StackTrace>
  <additionalInfo>
    <info name="MachineName" value="RPEREIRA" />
    <info name="TimeStamp" value="24/02/2016 17:04:06" />
    <info name="FullName" value="Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=4.1.0.0, Culture=neutral, PublicKeyToken=null" />
    <info name="AppDomainName" value="/LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-6-131008066966944141" />
    <info name="ThreadIdentity" value="" />
    <info name="WindowsIdentity" value="NT AUTHORITY\SYSTEM" />
  </additionalInfo>
</Exception>
Category: General
Priority: 0
EventId: 100
Severity: Error
Title:Enterprise Library Exception Handling
Machine: RPEREIRA
Application Domain: /LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-6-131008066966944141
Process Id: 26252
Process Name: C:\WINDOWS\SysWOW64\inetsrv\w3wp.exe
Win32 Thread Id: 11540
Thread Name: 
Extended Properties: 
----------------------------------------
----------------------------------------
Timestamp: 26/02/2016 15:54:41
Message: <Exception handlingInstanceId="ced94857-3d9f-417a-83a0-68d7f5d50371">
  <Description>An exception of type 'System.Data.OracleClient.OracleException' occurred and was caught.</Description>
  <DateTime>2016-02-26 15:54:41Z</DateTime>
  <ExceptionType>System.Data.OracleClient.OracleException, System.Data.OracleClient, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</ExceptionType>
  <Message>ORA-20005: CONTEXTO DE ACESSO INVALIDO
ORA-06512: at "ERESULTS_V2_DEV.PCK_ER_DOCS", line 311
ORA-06512: at "ERESULTS_V2_DEV.PCK_ER_DOCS", line 2431
ORA-06512: at line 1
</Message>
  <Source>System.Data.OracleClient</Source>
  <HelpLink />
  <Property name="Code">20005</Property>
  <Property name="ErrorCode">-2146232008</Property>
  <Property name="Data">System.Collections.ListDictionaryInternal</Property>
  <Property name="TargetSite">Void CheckError(System.Data.OracleClient.OciErrorHandle, Int32)</Property>
  <Property name="HResult">-2146232008</Property>
  <StackTrace>   at System.Data.OracleClient.OracleConnection.CheckError(OciErrorHandle errorHandle, Int32 rc)
   at System.Data.OracleClient.OracleCommand.Execute(OciStatementHandle statementHandle, CommandBehavior behavior, Boolean needRowid, OciRowidDescriptor&amp; rowidDescriptor, ArrayList&amp; resultParameterOrdinals)
   at System.Data.OracleClient.OracleCommand.Execute(OciStatementHandle statementHandle, CommandBehavior behavior, ArrayList&amp; resultParameterOrdinals)
   at System.Data.OracleClient.OracleCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.OracleClient.OracleCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.DoExecuteReader(DbCommand command, CommandBehavior cmdBehavior)
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.ExecuteReader(DbCommand command)
   at Microsoft.Practices.EnterpriseLibrary.Data.Oracle.OracleDatabase.ExecuteReader(DbCommand command)
   at Cpchs.Eresults.Common.WCF.BusinessEntities.DocumentManagementBER.GetDocsDB(String companyDB, String documentRef, String documentExternalId, String entitiesIds, String episodeType, String episodeId, String patientId, String patientType, Nullable`1 episodeStartDate, Nullable`1 episodeEndDate, String institution, String place, String application, String documentType, Nullable`1 executionStartDate, Nullable`1 executionEndDate, Nullable`1 validationStartDate, Nullable`1 validationEndDate, Nullable`1 emissionStartDate, Nullable`1 emissionEndDate, String reqService, String execService, String globalFilters, String docsSession, String servsSession, String username, Nullable`1 pageNumber, Nullable`1 itemsPerPage, String orderField, String orderType, String report, String isPublic, Nullable`1 workspaceId, String filterString, String period, Nullable`1&amp; resultCount) in d:\eResults\16R101\Glintths.Er.WebServices\Data\Glintths.Er.Common.Data\BusinessEntities\Documents\Document\DocumentManagementBER.cs:line 597</StackTrace>
  <additionalInfo>
    <info name="MachineName" value="RPEREIRA" />
    <info name="TimeStamp" value="26/02/2016 15:54:41" />
    <info name="FullName" value="Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=4.1.0.0, Culture=neutral, PublicKeyToken=null" />
    <info name="AppDomainName" value="/LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-9-131009756778481365" />
    <info name="ThreadIdentity" value="" />
    <info name="WindowsIdentity" value="NT AUTHORITY\SYSTEM" />
  </additionalInfo>
</Exception>
Category: General
Priority: 0
EventId: 100
Severity: Error
Title:Enterprise Library Exception Handling
Machine: RPEREIRA
Application Domain: /LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-9-131009756778481365
Process Id: 19392
Process Name: C:\WINDOWS\SysWOW64\inetsrv\w3wp.exe
Win32 Thread Id: 27768
Thread Name: 
Extended Properties: 
----------------------------------------
----------------------------------------
Timestamp: 03/03/2016 14:31:47
Message: <Exception handlingInstanceId="c4d802b8-44a2-4029-88ed-ea76548c377a">
  <Description>An exception of type 'System.Data.OracleClient.OracleException' occurred and was caught.</Description>
  <DateTime>2016-03-03 14:31:47Z</DateTime>
  <ExceptionType>System.Data.OracleClient.OracleException, System.Data.OracleClient, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</ExceptionType>
  <Message>ORA-20005: CONTEXTO DE ACESSO INVALIDO
ORA-06512: at "ERESULTS_V2_DEV.PCK_ER_DOCS", line 311
ORA-06512: at "ERESULTS_V2_DEV.PCK_ER_DOCS", line 2431
ORA-06512: at line 1
</Message>
  <Source>System.Data.OracleClient</Source>
  <HelpLink />
  <Property name="Code">20005</Property>
  <Property name="ErrorCode">-2146232008</Property>
  <Property name="Data">System.Collections.ListDictionaryInternal</Property>
  <Property name="TargetSite">Void CheckError(System.Data.OracleClient.OciErrorHandle, Int32)</Property>
  <Property name="HResult">-2146232008</Property>
  <StackTrace>   at System.Data.OracleClient.OracleConnection.CheckError(OciErrorHandle errorHandle, Int32 rc)
   at System.Data.OracleClient.OracleCommand.Execute(OciStatementHandle statementHandle, CommandBehavior behavior, Boolean needRowid, OciRowidDescriptor&amp; rowidDescriptor, ArrayList&amp; resultParameterOrdinals)
   at System.Data.OracleClient.OracleCommand.Execute(OciStatementHandle statementHandle, CommandBehavior behavior, ArrayList&amp; resultParameterOrdinals)
   at System.Data.OracleClient.OracleCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.OracleClient.OracleCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.DoExecuteReader(DbCommand command, CommandBehavior cmdBehavior)
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.ExecuteReader(DbCommand command)
   at Microsoft.Practices.EnterpriseLibrary.Data.Oracle.OracleDatabase.ExecuteReader(DbCommand command)
   at Cpchs.Eresults.Common.WCF.BusinessEntities.DocumentManagementBER.GetDocsDB(String companyDB, String documentRef, String documentExternalId, String entitiesIds, String episodeType, String episodeId, String patientId, String patientType, Nullable`1 episodeStartDate, Nullable`1 episodeEndDate, String institution, String place, String application, String documentType, Nullable`1 executionStartDate, Nullable`1 executionEndDate, Nullable`1 validationStartDate, Nullable`1 validationEndDate, Nullable`1 emissionStartDate, Nullable`1 emissionEndDate, String reqService, String execService, String globalFilters, String docsSession, String servsSession, String username, Nullable`1 pageNumber, Nullable`1 itemsPerPage, String orderField, String orderType, String report, String isPublic, Nullable`1 workspaceId, String filterString, String period, Nullable`1&amp; resultCount) in d:\eResults\16R101\Glintths.Er.WebServices\Data\Glintths.Er.Common.Data\BusinessEntities\Documents\Document\DocumentManagementBER.cs:line 602</StackTrace>
  <additionalInfo>
    <info name="MachineName" value="RPEREIRA" />
    <info name="TimeStamp" value="03/03/2016 14:31:47" />
    <info name="FullName" value="Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=4.1.0.0, Culture=neutral, PublicKeyToken=null" />
    <info name="AppDomainName" value="/LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-7-131014860143061162" />
    <info name="ThreadIdentity" value="" />
    <info name="WindowsIdentity" value="NT AUTHORITY\SYSTEM" />
  </additionalInfo>
</Exception>
Category: General
Priority: 0
EventId: 100
Severity: Error
Title:Enterprise Library Exception Handling
Machine: RPEREIRA
Application Domain: /LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-7-131014860143061162
Process Id: 7832
Process Name: C:\WINDOWS\SysWOW64\inetsrv\w3wp.exe
Win32 Thread Id: 4444
Thread Name: 
Extended Properties: 
----------------------------------------
----------------------------------------
Timestamp: 03/03/2016 14:53:36
Message: <Exception handlingInstanceId="e9a1e76c-35ab-452b-8b9c-535f5e3d95f1">
  <Description>An exception of type 'System.Data.OracleClient.OracleException' occurred and was caught.</Description>
  <DateTime>2016-03-03 14:53:35Z</DateTime>
  <ExceptionType>System.Data.OracleClient.OracleException, System.Data.OracleClient, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</ExceptionType>
  <Message>ORA-20005: CONTEXTO DE ACESSO INVALIDO
ORA-06512: at "ERESULTS_V2_DEV.PCK_ER_DOCS", line 311
ORA-06512: at "ERESULTS_V2_DEV.PCK_ER_DOCS", line 2431
ORA-06512: at line 1
</Message>
  <Source>System.Data.OracleClient</Source>
  <HelpLink />
  <Property name="Code">20005</Property>
  <Property name="ErrorCode">-2146232008</Property>
  <Property name="Data">System.Collections.ListDictionaryInternal</Property>
  <Property name="TargetSite">Void CheckError(System.Data.OracleClient.OciErrorHandle, Int32)</Property>
  <Property name="HResult">-2146232008</Property>
  <StackTrace>   at System.Data.OracleClient.OracleConnection.CheckError(OciErrorHandle errorHandle, Int32 rc)
   at System.Data.OracleClient.OracleCommand.Execute(OciStatementHandle statementHandle, CommandBehavior behavior, Boolean needRowid, OciRowidDescriptor&amp; rowidDescriptor, ArrayList&amp; resultParameterOrdinals)
   at System.Data.OracleClient.OracleCommand.Execute(OciStatementHandle statementHandle, CommandBehavior behavior, ArrayList&amp; resultParameterOrdinals)
   at System.Data.OracleClient.OracleCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.OracleClient.OracleCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.DoExecuteReader(DbCommand command, CommandBehavior cmdBehavior)
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.ExecuteReader(DbCommand command)
   at Microsoft.Practices.EnterpriseLibrary.Data.Oracle.OracleDatabase.ExecuteReader(DbCommand command)
   at Cpchs.Eresults.Common.WCF.BusinessEntities.DocumentManagementBER.GetDocsDB(String companyDB, String documentRef, String documentExternalId, String entitiesIds, String episodeType, String episodeId, String patientId, String patientType, Nullable`1 episodeStartDate, Nullable`1 episodeEndDate, String institution, String place, String application, String documentType, Nullable`1 executionStartDate, Nullable`1 executionEndDate, Nullable`1 validationStartDate, Nullable`1 validationEndDate, Nullable`1 emissionStartDate, Nullable`1 emissionEndDate, String reqService, String execService, String globalFilters, String docsSession, String servsSession, String username, Nullable`1 pageNumber, Nullable`1 itemsPerPage, String orderField, String orderType, String report, String isPublic, Nullable`1 workspaceId, String filterString, String period, Nullable`1&amp; resultCount) in d:\eResults\16R101\Glintths.Er.WebServices\Data\Glintths.Er.Common.Data\BusinessEntities\Documents\Document\DocumentManagementBER.cs:line 602</StackTrace>
  <additionalInfo>
    <info name="MachineName" value="RPEREIRA" />
    <info name="TimeStamp" value="03/03/2016 14:53:36" />
    <info name="FullName" value="Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=4.1.0.0, Culture=neutral, PublicKeyToken=null" />
    <info name="AppDomainName" value="/LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-7-131014900997049981" />
    <info name="ThreadIdentity" value="" />
    <info name="WindowsIdentity" value="NT AUTHORITY\SYSTEM" />
  </additionalInfo>
</Exception>
Category: General
Priority: 0
EventId: 100
Severity: Error
Title:Enterprise Library Exception Handling
Machine: RPEREIRA
Application Domain: /LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-7-131014900997049981
Process Id: 25828
Process Name: C:\WINDOWS\SysWOW64\inetsrv\w3wp.exe
Win32 Thread Id: 3796
Thread Name: 
Extended Properties: 
----------------------------------------
----------------------------------------
Timestamp: 04/03/2016 09:25:26
Message: <Exception handlingInstanceId="f26365c5-b14f-415f-8164-7f18b20eb024">
  <Description>An exception of type 'System.Data.OracleClient.OracleException' occurred and was caught.</Description>
  <DateTime>2016-03-04 09:25:26Z</DateTime>
  <ExceptionType>System.Data.OracleClient.OracleException, System.Data.OracleClient, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</ExceptionType>
  <Message>ORA-20005: CONTEXTO DE ACESSO INVALIDO
ORA-06512: at "ERESULTS_V2_DEV.PCK_ER_DOCS", line 311
ORA-06512: at "ERESULTS_V2_DEV.PCK_ER_DOCS", line 2431
ORA-06512: at line 1
</Message>
  <Source>System.Data.OracleClient</Source>
  <HelpLink />
  <Property name="Code">20005</Property>
  <Property name="ErrorCode">-2146232008</Property>
  <Property name="Data">System.Collections.ListDictionaryInternal</Property>
  <Property name="TargetSite">Void CheckError(System.Data.OracleClient.OciErrorHandle, Int32)</Property>
  <Property name="HResult">-2146232008</Property>
  <StackTrace>   at System.Data.OracleClient.OracleConnection.CheckError(OciErrorHandle errorHandle, Int32 rc)
   at System.Data.OracleClient.OracleCommand.Execute(OciStatementHandle statementHandle, CommandBehavior behavior, Boolean needRowid, OciRowidDescriptor&amp; rowidDescriptor, ArrayList&amp; resultParameterOrdinals)
   at System.Data.OracleClient.OracleCommand.Execute(OciStatementHandle statementHandle, CommandBehavior behavior, ArrayList&amp; resultParameterOrdinals)
   at System.Data.OracleClient.OracleCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.OracleClient.OracleCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.DoExecuteReader(DbCommand command, CommandBehavior cmdBehavior)
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.ExecuteReader(DbCommand command)
   at Microsoft.Practices.EnterpriseLibrary.Data.Oracle.OracleDatabase.ExecuteReader(DbCommand command)
   at Cpchs.Eresults.Common.WCF.BusinessEntities.DocumentManagementBER.GetDocsDB(String companyDB, String documentRef, String documentExternalId, String entitiesIds, String episodeType, String episodeId, String patientId, String patientType, Nullable`1 episodeStartDate, Nullable`1 episodeEndDate, String institution, String place, String application, String documentType, Nullable`1 executionStartDate, Nullable`1 executionEndDate, Nullable`1 validationStartDate, Nullable`1 validationEndDate, Nullable`1 emissionStartDate, Nullable`1 emissionEndDate, String reqService, String execService, String globalFilters, String docsSession, String servsSession, String username, Nullable`1 pageNumber, Nullable`1 itemsPerPage, String orderField, String orderType, String report, String isPublic, Nullable`1 workspaceId, String filterString, String period, Nullable`1&amp; resultCount) in d:\eResults\16R101\Glintths.Er.WebServices\Data\Glintths.Er.Common.Data\BusinessEntities\Documents\Document\DocumentManagementBER.cs:line 602</StackTrace>
  <additionalInfo>
    <info name="MachineName" value="RPEREIRA" />
    <info name="TimeStamp" value="04/03/2016 09:25:26" />
    <info name="FullName" value="Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=4.1.0.0, Culture=neutral, PublicKeyToken=null" />
    <info name="AppDomainName" value="/LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-10-131015569727636343" />
    <info name="ThreadIdentity" value="" />
    <info name="WindowsIdentity" value="NT AUTHORITY\SYSTEM" />
  </additionalInfo>
</Exception>
Category: General
Priority: 0
EventId: 100
Severity: Error
Title:Enterprise Library Exception Handling
Machine: RPEREIRA
Application Domain: /LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-10-131015569727636343
Process Id: 9272
Process Name: C:\WINDOWS\SysWOW64\inetsrv\w3wp.exe
Win32 Thread Id: 6824
Thread Name: 
Extended Properties: 
----------------------------------------
----------------------------------------
Timestamp: 04/03/2016 09:55:38
Message: <Exception handlingInstanceId="e0caa258-278c-4c86-8f75-b432a6ba1d33">
  <Description>An exception of type 'System.Data.OracleClient.OracleException' occurred and was caught.</Description>
  <DateTime>2016-03-04 09:55:38Z</DateTime>
  <ExceptionType>System.Data.OracleClient.OracleException, System.Data.OracleClient, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</ExceptionType>
  <Message>ORA-20005: CONTEXTO DE ACESSO INVALIDO
ORA-06512: at "ERESULTS_V2_DEV.PCK_ER_DOCS", line 311
ORA-06512: at "ERESULTS_V2_DEV.PCK_ER_DOCS", line 2431
ORA-06512: at line 1
</Message>
  <Source>System.Data.OracleClient</Source>
  <HelpLink />
  <Property name="Code">20005</Property>
  <Property name="ErrorCode">-2146232008</Property>
  <Property name="Data">System.Collections.ListDictionaryInternal</Property>
  <Property name="TargetSite">Void CheckError(System.Data.OracleClient.OciErrorHandle, Int32)</Property>
  <Property name="HResult">-2146232008</Property>
  <StackTrace>   at System.Data.OracleClient.OracleConnection.CheckError(OciErrorHandle errorHandle, Int32 rc)
   at System.Data.OracleClient.OracleCommand.Execute(OciStatementHandle statementHandle, CommandBehavior behavior, Boolean needRowid, OciRowidDescriptor&amp; rowidDescriptor, ArrayList&amp; resultParameterOrdinals)
   at System.Data.OracleClient.OracleCommand.Execute(OciStatementHandle statementHandle, CommandBehavior behavior, ArrayList&amp; resultParameterOrdinals)
   at System.Data.OracleClient.OracleCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.OracleClient.OracleCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.DoExecuteReader(DbCommand command, CommandBehavior cmdBehavior)
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.ExecuteReader(DbCommand command)
   at Microsoft.Practices.EnterpriseLibrary.Data.Oracle.OracleDatabase.ExecuteReader(DbCommand command)
   at Cpchs.Eresults.Common.WCF.BusinessEntities.DocumentManagementBER.GetDocsDB(String companyDB, String documentRef, String documentExternalId, String entitiesIds, String episodeType, String episodeId, String patientId, String patientType, Nullable`1 episodeStartDate, Nullable`1 episodeEndDate, String institution, String place, String application, String documentType, Nullable`1 executionStartDate, Nullable`1 executionEndDate, Nullable`1 validationStartDate, Nullable`1 validationEndDate, Nullable`1 emissionStartDate, Nullable`1 emissionEndDate, String reqService, String execService, String globalFilters, String docsSession, String servsSession, String username, Nullable`1 pageNumber, Nullable`1 itemsPerPage, String orderField, String orderType, String report, String isPublic, Nullable`1 workspaceId, String filterString, String period, Nullable`1&amp; resultCount) in d:\eResults\16R101\Glintths.Er.WebServices\Data\Glintths.Er.Common.Data\BusinessEntities\Documents\Document\DocumentManagementBER.cs:line 602</StackTrace>
  <additionalInfo>
    <info name="MachineName" value="RPEREIRA" />
    <info name="TimeStamp" value="04/03/2016 09:55:38" />
    <info name="FullName" value="Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=4.1.0.0, Culture=neutral, PublicKeyToken=null" />
    <info name="AppDomainName" value="/LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-8-131015589370493835" />
    <info name="ThreadIdentity" value="" />
    <info name="WindowsIdentity" value="NT AUTHORITY\SYSTEM" />
  </additionalInfo>
</Exception>
Category: General
Priority: 0
EventId: 100
Severity: Error
Title:Enterprise Library Exception Handling
Machine: RPEREIRA
Application Domain: /LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-8-131015589370493835
Process Id: 27472
Process Name: C:\WINDOWS\SysWOW64\inetsrv\w3wp.exe
Win32 Thread Id: 5304
Thread Name: 
Extended Properties: 
----------------------------------------
----------------------------------------
Timestamp: 04/03/2016 15:13:18
Message: <Exception handlingInstanceId="f828e082-bfde-40f4-bd89-a5da747e9230">
  <Description>An exception of type 'System.Data.OracleClient.OracleException' occurred and was caught.</Description>
  <DateTime>2016-03-04 15:13:18Z</DateTime>
  <ExceptionType>System.Data.OracleClient.OracleException, System.Data.OracleClient, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</ExceptionType>
  <Message>ORA-20005: CONTEXTO DE ACESSO INVALIDO
ORA-06512: at "ERESULTS_V2_DEV.PCK_ER_DOCS", line 311
ORA-06512: at "ERESULTS_V2_DEV.PCK_ER_DOCS", line 2431
ORA-06512: at line 1
</Message>
  <Source>System.Data.OracleClient</Source>
  <HelpLink />
  <Property name="Code">20005</Property>
  <Property name="ErrorCode">-2146232008</Property>
  <Property name="Data">System.Collections.ListDictionaryInternal</Property>
  <Property name="TargetSite">Void CheckError(System.Data.OracleClient.OciErrorHandle, Int32)</Property>
  <Property name="HResult">-2146232008</Property>
  <StackTrace>   at System.Data.OracleClient.OracleConnection.CheckError(OciErrorHandle errorHandle, Int32 rc)
   at System.Data.OracleClient.OracleCommand.Execute(OciStatementHandle statementHandle, CommandBehavior behavior, Boolean needRowid, OciRowidDescriptor&amp; rowidDescriptor, ArrayList&amp; resultParameterOrdinals)
   at System.Data.OracleClient.OracleCommand.Execute(OciStatementHandle statementHandle, CommandBehavior behavior, ArrayList&amp; resultParameterOrdinals)
   at System.Data.OracleClient.OracleCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.OracleClient.OracleCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.DoExecuteReader(DbCommand command, CommandBehavior cmdBehavior)
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.ExecuteReader(DbCommand command)
   at Microsoft.Practices.EnterpriseLibrary.Data.Oracle.OracleDatabase.ExecuteReader(DbCommand command)
   at Cpchs.Eresults.Common.WCF.BusinessEntities.DocumentManagementBER.GetDocsDB(String companyDB, String documentRef, String documentExternalId, String entitiesIds, String episodeType, String episodeId, String patientId, String patientType, Nullable`1 episodeStartDate, Nullable`1 episodeEndDate, String institution, String place, String application, String documentType, Nullable`1 executionStartDate, Nullable`1 executionEndDate, Nullable`1 validationStartDate, Nullable`1 validationEndDate, Nullable`1 emissionStartDate, Nullable`1 emissionEndDate, String reqService, String execService, String globalFilters, String docsSession, String servsSession, String username, Nullable`1 pageNumber, Nullable`1 itemsPerPage, String orderField, String orderType, String report, String isPublic, Nullable`1 workspaceId, String filterString, String period, Nullable`1&amp; resultCount) in d:\eResults\16R101\Glintths.Er.WebServices\Data\Glintths.Er.Common.Data\BusinessEntities\Documents\Document\DocumentManagementBER.cs:line 602</StackTrace>
  <additionalInfo>
    <info name="MachineName" value="RPEREIRA" />
    <info name="TimeStamp" value="04/03/2016 15:13:18" />
    <info name="FullName" value="Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=4.1.0.0, Culture=neutral, PublicKeyToken=null" />
    <info name="AppDomainName" value="/LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-8-131015589370493835" />
    <info name="ThreadIdentity" value="" />
    <info name="WindowsIdentity" value="NT AUTHORITY\SYSTEM" />
  </additionalInfo>
</Exception>
Category: General
Priority: 0
EventId: 100
Severity: Error
Title:Enterprise Library Exception Handling
Machine: RPEREIRA
Application Domain: /LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-8-131015589370493835
Process Id: 27472
Process Name: C:\WINDOWS\SysWOW64\inetsrv\w3wp.exe
Win32 Thread Id: 12168
Thread Name: 
Extended Properties: 
----------------------------------------
----------------------------------------
Timestamp: 04/03/2016 15:39:05
Message: <Exception handlingInstanceId="3ef55859-e6bd-4c93-a4bf-43e167c99696">
  <Description>An exception of type 'System.Data.OracleClient.OracleException' occurred and was caught.</Description>
  <DateTime>2016-03-04 15:39:05Z</DateTime>
  <ExceptionType>System.Data.OracleClient.OracleException, System.Data.OracleClient, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</ExceptionType>
  <Message>ORA-20005: CONTEXTO DE ACESSO INVALIDO
ORA-06512: at "ERESULTS_V2_DEV.PCK_ER_DOCS", line 311
ORA-06512: at "ERESULTS_V2_DEV.PCK_ER_DOCS", line 2431
ORA-06512: at line 1
</Message>
  <Source>System.Data.OracleClient</Source>
  <HelpLink />
  <Property name="Code">20005</Property>
  <Property name="ErrorCode">-2146232008</Property>
  <Property name="Data">System.Collections.ListDictionaryInternal</Property>
  <Property name="TargetSite">Void CheckError(System.Data.OracleClient.OciErrorHandle, Int32)</Property>
  <Property name="HResult">-2146232008</Property>
  <StackTrace>   at System.Data.OracleClient.OracleConnection.CheckError(OciErrorHandle errorHandle, Int32 rc)
   at System.Data.OracleClient.OracleCommand.Execute(OciStatementHandle statementHandle, CommandBehavior behavior, Boolean needRowid, OciRowidDescriptor&amp; rowidDescriptor, ArrayList&amp; resultParameterOrdinals)
   at System.Data.OracleClient.OracleCommand.Execute(OciStatementHandle statementHandle, CommandBehavior behavior, ArrayList&amp; resultParameterOrdinals)
   at System.Data.OracleClient.OracleCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.OracleClient.OracleCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.DoExecuteReader(DbCommand command, CommandBehavior cmdBehavior)
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.ExecuteReader(DbCommand command)
   at Microsoft.Practices.EnterpriseLibrary.Data.Oracle.OracleDatabase.ExecuteReader(DbCommand command)
   at Cpchs.Eresults.Common.WCF.BusinessEntities.DocumentManagementBER.GetDocsDB(String companyDB, String documentRef, String documentExternalId, String entitiesIds, String episodeType, String episodeId, String patientId, String patientType, Nullable`1 episodeStartDate, Nullable`1 episodeEndDate, String institution, String place, String application, String documentType, Nullable`1 executionStartDate, Nullable`1 executionEndDate, Nullable`1 validationStartDate, Nullable`1 validationEndDate, Nullable`1 emissionStartDate, Nullable`1 emissionEndDate, String reqService, String execService, String globalFilters, String docsSession, String servsSession, String username, Nullable`1 pageNumber, Nullable`1 itemsPerPage, String orderField, String orderType, String report, String isPublic, Nullable`1 workspaceId, String filterString, String period, Nullable`1&amp; resultCount) in d:\eResults\16R101\Glintths.Er.WebServices\Data\Glintths.Er.Common.Data\BusinessEntities\Documents\Document\DocumentManagementBER.cs:line 602</StackTrace>
  <additionalInfo>
    <info name="MachineName" value="RPEREIRA" />
    <info name="TimeStamp" value="04/03/2016 15:39:05" />
    <info name="FullName" value="Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=4.1.0.0, Culture=neutral, PublicKeyToken=null" />
    <info name="AppDomainName" value="/LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-8-131015589370493835" />
    <info name="ThreadIdentity" value="" />
    <info name="WindowsIdentity" value="NT AUTHORITY\SYSTEM" />
  </additionalInfo>
</Exception>
Category: General
Priority: 0
EventId: 100
Severity: Error
Title:Enterprise Library Exception Handling
Machine: RPEREIRA
Application Domain: /LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-8-131015589370493835
Process Id: 27472
Process Name: C:\WINDOWS\SysWOW64\inetsrv\w3wp.exe
Win32 Thread Id: 1784
Thread Name: 
Extended Properties: 
----------------------------------------
----------------------------------------
Timestamp: 16/03/2016 17:36:46
Message: <Exception handlingInstanceId="e82a7d1c-a00f-498f-8ee2-4996820b5568">
  <Description>An exception of type 'System.Data.OracleClient.OracleException' occurred and was caught.</Description>
  <DateTime>2016-03-16 17:36:46Z</DateTime>
  <ExceptionType>System.Data.OracleClient.OracleException, System.Data.OracleClient, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</ExceptionType>
  <Message>ORA-20005: CONTEXTO DE ACESSO INVALIDO
ORA-06512: at "ERESULTS_V2_DEV.PCK_ER_DOCS", line 311
ORA-06512: at "ERESULTS_V2_DEV.PCK_ER_DOCS", line 2431
ORA-06512: at line 1
</Message>
  <Source>System.Data.OracleClient</Source>
  <HelpLink />
  <Property name="Code">20005</Property>
  <Property name="ErrorCode">-2146232008</Property>
  <Property name="Data">System.Collections.ListDictionaryInternal</Property>
  <Property name="TargetSite">Void CheckError(System.Data.OracleClient.OciErrorHandle, Int32)</Property>
  <Property name="HResult">-2146232008</Property>
  <StackTrace>   at System.Data.OracleClient.OracleConnection.CheckError(OciErrorHandle errorHandle, Int32 rc)
   at System.Data.OracleClient.OracleCommand.Execute(OciStatementHandle statementHandle, CommandBehavior behavior, Boolean needRowid, OciRowidDescriptor&amp; rowidDescriptor, ArrayList&amp; resultParameterOrdinals)
   at System.Data.OracleClient.OracleCommand.Execute(OciStatementHandle statementHandle, CommandBehavior behavior, ArrayList&amp; resultParameterOrdinals)
   at System.Data.OracleClient.OracleCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.OracleClient.OracleCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.DoExecuteReader(DbCommand command, CommandBehavior cmdBehavior)
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.ExecuteReader(DbCommand command)
   at Microsoft.Practices.EnterpriseLibrary.Data.Oracle.OracleDatabase.ExecuteReader(DbCommand command)
   at Cpchs.Eresults.Common.WCF.BusinessEntities.DocumentManagementBER.GetDocsDB(String companyDB, String documentRef, String documentExternalId, String entitiesIds, String episodeType, String episodeId, String patientId, String patientType, Nullable`1 episodeStartDate, Nullable`1 episodeEndDate, String institution, String place, String application, String documentType, Nullable`1 executionStartDate, Nullable`1 executionEndDate, Nullable`1 validationStartDate, Nullable`1 validationEndDate, Nullable`1 emissionStartDate, Nullable`1 emissionEndDate, String reqService, String execService, String globalFilters, String docsSession, String servsSession, String username, Nullable`1 pageNumber, Nullable`1 itemsPerPage, String orderField, String orderType, String report, String isPublic, Nullable`1 workspaceId, String filterString, String period, Nullable`1&amp; resultCount) in d:\eResults\16R101\Glintths.Er.WebServices\Data\Glintths.Er.Common.Data\BusinessEntities\Documents\Document\DocumentManagementBER.cs:line 602</StackTrace>
  <additionalInfo>
    <info name="MachineName" value="RPEREIRA" />
    <info name="TimeStamp" value="16/03/2016 17:36:46" />
    <info name="FullName" value="Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=4.1.0.0, Culture=neutral, PublicKeyToken=null" />
    <info name="AppDomainName" value="/LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-14-131026234039496796" />
    <info name="ThreadIdentity" value="" />
    <info name="WindowsIdentity" value="NT AUTHORITY\SYSTEM" />
  </additionalInfo>
</Exception>
Category: General
Priority: 0
EventId: 100
Severity: Error
Title:Enterprise Library Exception Handling
Machine: RPEREIRA
Application Domain: /LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-14-131026234039496796
Process Id: 8204
Process Name: C:\WINDOWS\SysWOW64\inetsrv\w3wp.exe
Win32 Thread Id: 12720
Thread Name: 
Extended Properties: 
----------------------------------------
----------------------------------------
Timestamp: 16/03/2016 17:37:29
Message: <Exception handlingInstanceId="9605f7d8-dd08-4fa4-b1d9-dc8bcbb00efd">
  <Description>An exception of type 'System.Data.OracleClient.OracleException' occurred and was caught.</Description>
  <DateTime>2016-03-16 17:37:29Z</DateTime>
  <ExceptionType>System.Data.OracleClient.OracleException, System.Data.OracleClient, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</ExceptionType>
  <Message>ORA-20005: CONTEXTO DE ACESSO INVALIDO
ORA-06512: at "ERESULTS_V2_DEV.PCK_ER_DOCS", line 860
ORA-06512: at "ERESULTS_V2_DEV.PCK_ER_DOCS", line 1423
ORA-06512: at line 1
</Message>
  <Source>System.Data.OracleClient</Source>
  <HelpLink />
  <Property name="Code">20005</Property>
  <Property name="ErrorCode">-2146232008</Property>
  <Property name="Data">System.Collections.ListDictionaryInternal</Property>
  <Property name="TargetSite">Void CheckError(System.Data.OracleClient.OciErrorHandle, Int32)</Property>
  <Property name="HResult">-2146232008</Property>
  <StackTrace>   at System.Data.OracleClient.OracleConnection.CheckError(OciErrorHandle errorHandle, Int32 rc)
   at System.Data.OracleClient.OracleCommand.Execute(OciStatementHandle statementHandle, CommandBehavior behavior, Boolean needRowid, OciRowidDescriptor&amp; rowidDescriptor, ArrayList&amp; resultParameterOrdinals)
   at System.Data.OracleClient.OracleCommand.Execute(OciStatementHandle statementHandle, CommandBehavior behavior, ArrayList&amp; resultParameterOrdinals)
   at System.Data.OracleClient.OracleCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.OracleClient.OracleCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.DoExecuteReader(DbCommand command, CommandBehavior cmdBehavior)
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.ExecuteReader(DbCommand command)
   at Microsoft.Practices.EnterpriseLibrary.Data.Oracle.OracleDatabase.ExecuteReader(DbCommand command)
   at Cpchs.Eresults.Common.WCF.BusinessEntities.DocumentManagementBER.GetDocumentsToCancelDB(String companyDB, String documentRef, String documentExternalId, String entitiesIds, String episodeType, String episodeId, String patientId, String patientType, Nullable`1 episodeStartDate, Nullable`1 episodeEndDate, String institution, String place, String application, String documentType, Nullable`1 executionStartDate, Nullable`1 executionEndDate, Nullable`1 validationStartDate, Nullable`1 validationEndDate, Nullable`1 emissionStartDate, Nullable`1 emissionEndDate, String reqService, String execService, String globalFilters, String docsSession, String servsSession, String username, Nullable`1 pageNumber, Nullable`1 itemsPerPage, String orderField, String orderType, String report, String isPublic, Nullable`1 workspaceId, String filterString, String period, Nullable`1&amp; resultCount) in d:\eResults\16R101\Glintths.Er.WebServices\Data\Glintths.Er.Common.Data\BusinessEntities\Documents\Document\DocumentManagementBER.cs:line 652</StackTrace>
  <additionalInfo>
    <info name="MachineName" value="RPEREIRA" />
    <info name="TimeStamp" value="16/03/2016 17:37:29" />
    <info name="FullName" value="Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=4.1.0.0, Culture=neutral, PublicKeyToken=null" />
    <info name="AppDomainName" value="/LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-14-131026234039496796" />
    <info name="ThreadIdentity" value="" />
    <info name="WindowsIdentity" value="NT AUTHORITY\SYSTEM" />
  </additionalInfo>
</Exception>
Category: General
Priority: 0
EventId: 100
Severity: Error
Title:Enterprise Library Exception Handling
Machine: RPEREIRA
Application Domain: /LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-14-131026234039496796
Process Id: 8204
Process Name: C:\WINDOWS\SysWOW64\inetsrv\w3wp.exe
Win32 Thread Id: 9228
Thread Name: 
Extended Properties: 
----------------------------------------
----------------------------------------
Timestamp: 16/03/2016 17:38:02
Message: <Exception handlingInstanceId="5d7cc15a-fe7d-43cb-8419-a0da7bc94ebb">
  <Description>An exception of type 'System.Data.OracleClient.OracleException' occurred and was caught.</Description>
  <DateTime>2016-03-16 17:38:02Z</DateTime>
  <ExceptionType>System.Data.OracleClient.OracleException, System.Data.OracleClient, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</ExceptionType>
  <Message>ORA-20005: CONTEXTO DE ACESSO INVALIDO
ORA-06512: at "ERESULTS_V2_DEV.PCK_ER_DOCS", line 311
ORA-06512: at "ERESULTS_V2_DEV.PCK_ER_DOCS", line 2431
ORA-06512: at line 1
</Message>
  <Source>System.Data.OracleClient</Source>
  <HelpLink />
  <Property name="Code">20005</Property>
  <Property name="ErrorCode">-2146232008</Property>
  <Property name="Data">System.Collections.ListDictionaryInternal</Property>
  <Property name="TargetSite">Void CheckError(System.Data.OracleClient.OciErrorHandle, Int32)</Property>
  <Property name="HResult">-2146232008</Property>
  <StackTrace>   at System.Data.OracleClient.OracleConnection.CheckError(OciErrorHandle errorHandle, Int32 rc)
   at System.Data.OracleClient.OracleCommand.Execute(OciStatementHandle statementHandle, CommandBehavior behavior, Boolean needRowid, OciRowidDescriptor&amp; rowidDescriptor, ArrayList&amp; resultParameterOrdinals)
   at System.Data.OracleClient.OracleCommand.Execute(OciStatementHandle statementHandle, CommandBehavior behavior, ArrayList&amp; resultParameterOrdinals)
   at System.Data.OracleClient.OracleCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.OracleClient.OracleCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.DoExecuteReader(DbCommand command, CommandBehavior cmdBehavior)
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.ExecuteReader(DbCommand command)
   at Microsoft.Practices.EnterpriseLibrary.Data.Oracle.OracleDatabase.ExecuteReader(DbCommand command)
   at Cpchs.Eresults.Common.WCF.BusinessEntities.DocumentManagementBER.GetDocsDB(String companyDB, String documentRef, String documentExternalId, String entitiesIds, String episodeType, String episodeId, String patientId, String patientType, Nullable`1 episodeStartDate, Nullable`1 episodeEndDate, String institution, String place, String application, String documentType, Nullable`1 executionStartDate, Nullable`1 executionEndDate, Nullable`1 validationStartDate, Nullable`1 validationEndDate, Nullable`1 emissionStartDate, Nullable`1 emissionEndDate, String reqService, String execService, String globalFilters, String docsSession, String servsSession, String username, Nullable`1 pageNumber, Nullable`1 itemsPerPage, String orderField, String orderType, String report, String isPublic, Nullable`1 workspaceId, String filterString, String period, Nullable`1&amp; resultCount) in d:\eResults\16R101\Glintths.Er.WebServices\Data\Glintths.Er.Common.Data\BusinessEntities\Documents\Document\DocumentManagementBER.cs:line 602</StackTrace>
  <additionalInfo>
    <info name="MachineName" value="RPEREIRA" />
    <info name="TimeStamp" value="16/03/2016 17:38:02" />
    <info name="FullName" value="Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=4.1.0.0, Culture=neutral, PublicKeyToken=null" />
    <info name="AppDomainName" value="/LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-14-131026234039496796" />
    <info name="ThreadIdentity" value="" />
    <info name="WindowsIdentity" value="NT AUTHORITY\SYSTEM" />
  </additionalInfo>
</Exception>
Category: General
Priority: 0
EventId: 100
Severity: Error
Title:Enterprise Library Exception Handling
Machine: RPEREIRA
Application Domain: /LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-14-131026234039496796
Process Id: 8204
Process Name: C:\WINDOWS\SysWOW64\inetsrv\w3wp.exe
Win32 Thread Id: 10080
Thread Name: 
Extended Properties: 
----------------------------------------
----------------------------------------
Timestamp: 16/03/2016 17:40:12
Message: <Exception handlingInstanceId="c0d8113c-9ab4-412b-bf6b-d5171f5f361b">
  <Description>An exception of type 'System.Data.OracleClient.OracleException' occurred and was caught.</Description>
  <DateTime>2016-03-16 17:40:12Z</DateTime>
  <ExceptionType>System.Data.OracleClient.OracleException, System.Data.OracleClient, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</ExceptionType>
  <Message>ORA-20005: CONTEXTO DE ACESSO INVALIDO
ORA-06512: at "ERESULTS_V2_DEV.PCK_ER_DOCS", line 311
ORA-06512: at "ERESULTS_V2_DEV.PCK_ER_DOCS", line 2431
ORA-06512: at line 1
</Message>
  <Source>System.Data.OracleClient</Source>
  <HelpLink />
  <Property name="Code">20005</Property>
  <Property name="ErrorCode">-2146232008</Property>
  <Property name="Data">System.Collections.ListDictionaryInternal</Property>
  <Property name="TargetSite">Void CheckError(System.Data.OracleClient.OciErrorHandle, Int32)</Property>
  <Property name="HResult">-2146232008</Property>
  <StackTrace>   at System.Data.OracleClient.OracleConnection.CheckError(OciErrorHandle errorHandle, Int32 rc)
   at System.Data.OracleClient.OracleCommand.Execute(OciStatementHandle statementHandle, CommandBehavior behavior, Boolean needRowid, OciRowidDescriptor&amp; rowidDescriptor, ArrayList&amp; resultParameterOrdinals)
   at System.Data.OracleClient.OracleCommand.Execute(OciStatementHandle statementHandle, CommandBehavior behavior, ArrayList&amp; resultParameterOrdinals)
   at System.Data.OracleClient.OracleCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.OracleClient.OracleCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.DoExecuteReader(DbCommand command, CommandBehavior cmdBehavior)
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.ExecuteReader(DbCommand command)
   at Microsoft.Practices.EnterpriseLibrary.Data.Oracle.OracleDatabase.ExecuteReader(DbCommand command)
   at Cpchs.Eresults.Common.WCF.BusinessEntities.DocumentManagementBER.GetDocsDB(String companyDB, String documentRef, String documentExternalId, String entitiesIds, String episodeType, String episodeId, String patientId, String patientType, Nullable`1 episodeStartDate, Nullable`1 episodeEndDate, String institution, String place, String application, String documentType, Nullable`1 executionStartDate, Nullable`1 executionEndDate, Nullable`1 validationStartDate, Nullable`1 validationEndDate, Nullable`1 emissionStartDate, Nullable`1 emissionEndDate, String reqService, String execService, String globalFilters, String docsSession, String servsSession, String username, Nullable`1 pageNumber, Nullable`1 itemsPerPage, String orderField, String orderType, String report, String isPublic, Nullable`1 workspaceId, String filterString, String period, Nullable`1&amp; resultCount) in d:\eResults\16R101\Glintths.Er.WebServices\Data\Glintths.Er.Common.Data\BusinessEntities\Documents\Document\DocumentManagementBER.cs:line 602</StackTrace>
  <additionalInfo>
    <info name="MachineName" value="RPEREIRA" />
    <info name="TimeStamp" value="16/03/2016 17:40:12" />
    <info name="FullName" value="Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=4.1.0.0, Culture=neutral, PublicKeyToken=null" />
    <info name="AppDomainName" value="/LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-14-131026234039496796" />
    <info name="ThreadIdentity" value="" />
    <info name="WindowsIdentity" value="NT AUTHORITY\SYSTEM" />
  </additionalInfo>
</Exception>
Category: General
Priority: 0
EventId: 100
Severity: Error
Title:Enterprise Library Exception Handling
Machine: RPEREIRA
Application Domain: /LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-14-131026234039496796
Process Id: 8204
Process Name: C:\WINDOWS\SysWOW64\inetsrv\w3wp.exe
Win32 Thread Id: 2776
Thread Name: 
Extended Properties: 
----------------------------------------
----------------------------------------
Timestamp: 16/03/2016 17:46:52
Message: <Exception handlingInstanceId="51410101-9880-47b3-bd2a-0904a07877f2">
  <Description>An exception of type 'System.Data.OracleClient.OracleException' occurred and was caught.</Description>
  <DateTime>2016-03-16 17:46:52Z</DateTime>
  <ExceptionType>System.Data.OracleClient.OracleException, System.Data.OracleClient, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</ExceptionType>
  <Message>ORA-20005: CONTEXTO DE ACESSO INVALIDO
ORA-06512: at "ERESULTS_V2_DEV.PCK_ER_DOCS", line 311
ORA-06512: at "ERESULTS_V2_DEV.PCK_ER_DOCS", line 2431
ORA-06512: at line 1
</Message>
  <Source>System.Data.OracleClient</Source>
  <HelpLink />
  <Property name="Code">20005</Property>
  <Property name="ErrorCode">-2146232008</Property>
  <Property name="Data">System.Collections.ListDictionaryInternal</Property>
  <Property name="TargetSite">Void CheckError(System.Data.OracleClient.OciErrorHandle, Int32)</Property>
  <Property name="HResult">-2146232008</Property>
  <StackTrace>   at System.Data.OracleClient.OracleConnection.CheckError(OciErrorHandle errorHandle, Int32 rc)
   at System.Data.OracleClient.OracleCommand.Execute(OciStatementHandle statementHandle, CommandBehavior behavior, Boolean needRowid, OciRowidDescriptor&amp; rowidDescriptor, ArrayList&amp; resultParameterOrdinals)
   at System.Data.OracleClient.OracleCommand.Execute(OciStatementHandle statementHandle, CommandBehavior behavior, ArrayList&amp; resultParameterOrdinals)
   at System.Data.OracleClient.OracleCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.OracleClient.OracleCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.DoExecuteReader(DbCommand command, CommandBehavior cmdBehavior)
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.ExecuteReader(DbCommand command)
   at Microsoft.Practices.EnterpriseLibrary.Data.Oracle.OracleDatabase.ExecuteReader(DbCommand command)
   at Cpchs.Eresults.Common.WCF.BusinessEntities.DocumentManagementBER.GetDocsDB(String companyDB, String documentRef, String documentExternalId, String entitiesIds, String episodeType, String episodeId, String patientId, String patientType, Nullable`1 episodeStartDate, Nullable`1 episodeEndDate, String institution, String place, String application, String documentType, Nullable`1 executionStartDate, Nullable`1 executionEndDate, Nullable`1 validationStartDate, Nullable`1 validationEndDate, Nullable`1 emissionStartDate, Nullable`1 emissionEndDate, String reqService, String execService, String globalFilters, String docsSession, String servsSession, String username, Nullable`1 pageNumber, Nullable`1 itemsPerPage, String orderField, String orderType, String report, String isPublic, Nullable`1 workspaceId, String filterString, String period, Nullable`1&amp; resultCount) in d:\eResults\16R101\Glintths.Er.WebServices\Data\Glintths.Er.Common.Data\BusinessEntities\Documents\Document\DocumentManagementBER.cs:line 602</StackTrace>
  <additionalInfo>
    <info name="MachineName" value="RPEREIRA" />
    <info name="TimeStamp" value="16/03/2016 17:46:52" />
    <info name="FullName" value="Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=4.1.0.0, Culture=neutral, PublicKeyToken=null" />
    <info name="AppDomainName" value="/LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-14-131026234039496796" />
    <info name="ThreadIdentity" value="" />
    <info name="WindowsIdentity" value="NT AUTHORITY\SYSTEM" />
  </additionalInfo>
</Exception>
Category: General
Priority: 0
EventId: 100
Severity: Error
Title:Enterprise Library Exception Handling
Machine: RPEREIRA
Application Domain: /LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-14-131026234039496796
Process Id: 8204
Process Name: C:\WINDOWS\SysWOW64\inetsrv\w3wp.exe
Win32 Thread Id: 13156
Thread Name: 
Extended Properties: 
----------------------------------------
----------------------------------------
Timestamp: 16/03/2016 17:58:27
Message: <Exception handlingInstanceId="ce5218b9-722c-4fdf-be98-0a06de88112f">
  <Description>An exception of type 'System.Data.OracleClient.OracleException' occurred and was caught.</Description>
  <DateTime>2016-03-16 17:58:27Z</DateTime>
  <ExceptionType>System.Data.OracleClient.OracleException, System.Data.OracleClient, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</ExceptionType>
  <Message>ORA-20005: CONTEXTO DE ACESSO INVALIDO
ORA-06512: at "ERESULTS_V2_DEV.PCK_ER_DOCS", line 311
ORA-06512: at "ERESULTS_V2_DEV.PCK_ER_DOCS", line 2431
ORA-06512: at line 1
</Message>
  <Source>System.Data.OracleClient</Source>
  <HelpLink />
  <Property name="Code">20005</Property>
  <Property name="ErrorCode">-2146232008</Property>
  <Property name="Data">System.Collections.ListDictionaryInternal</Property>
  <Property name="TargetSite">Void CheckError(System.Data.OracleClient.OciErrorHandle, Int32)</Property>
  <Property name="HResult">-2146232008</Property>
  <StackTrace>   at System.Data.OracleClient.OracleConnection.CheckError(OciErrorHandle errorHandle, Int32 rc)
   at System.Data.OracleClient.OracleCommand.Execute(OciStatementHandle statementHandle, CommandBehavior behavior, Boolean needRowid, OciRowidDescriptor&amp; rowidDescriptor, ArrayList&amp; resultParameterOrdinals)
   at System.Data.OracleClient.OracleCommand.Execute(OciStatementHandle statementHandle, CommandBehavior behavior, ArrayList&amp; resultParameterOrdinals)
   at System.Data.OracleClient.OracleCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.OracleClient.OracleCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.DoExecuteReader(DbCommand command, CommandBehavior cmdBehavior)
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.ExecuteReader(DbCommand command)
   at Microsoft.Practices.EnterpriseLibrary.Data.Oracle.OracleDatabase.ExecuteReader(DbCommand command)
   at Cpchs.Eresults.Common.WCF.BusinessEntities.DocumentManagementBER.GetDocsDB(String companyDB, String documentRef, String documentExternalId, String entitiesIds, String episodeType, String episodeId, String patientId, String patientType, Nullable`1 episodeStartDate, Nullable`1 episodeEndDate, String institution, String place, String application, String documentType, Nullable`1 executionStartDate, Nullable`1 executionEndDate, Nullable`1 validationStartDate, Nullable`1 validationEndDate, Nullable`1 emissionStartDate, Nullable`1 emissionEndDate, String reqService, String execService, String globalFilters, String docsSession, String servsSession, String username, Nullable`1 pageNumber, Nullable`1 itemsPerPage, String orderField, String orderType, String report, String isPublic, Nullable`1 workspaceId, String filterString, String period, Nullable`1&amp; resultCount) in d:\eResults\16R101\Glintths.Er.WebServices\Data\Glintths.Er.Common.Data\BusinessEntities\Documents\Document\DocumentManagementBER.cs:line 602</StackTrace>
  <additionalInfo>
    <info name="MachineName" value="RPEREIRA" />
    <info name="TimeStamp" value="16/03/2016 17:58:27" />
    <info name="FullName" value="Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=4.1.0.0, Culture=neutral, PublicKeyToken=null" />
    <info name="AppDomainName" value="/LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-14-131026234039496796" />
    <info name="ThreadIdentity" value="" />
    <info name="WindowsIdentity" value="NT AUTHORITY\SYSTEM" />
  </additionalInfo>
</Exception>
Category: General
Priority: 0
EventId: 100
Severity: Error
Title:Enterprise Library Exception Handling
Machine: RPEREIRA
Application Domain: /LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-14-131026234039496796
Process Id: 8204
Process Name: C:\WINDOWS\SysWOW64\inetsrv\w3wp.exe
Win32 Thread Id: 848
Thread Name: 
Extended Properties: 
----------------------------------------
----------------------------------------
Timestamp: 16/03/2016 18:04:11
Message: <Exception handlingInstanceId="9c181e50-f851-48d1-b29c-a17dc4384cb3">
  <Description>An exception of type 'System.Data.OracleClient.OracleException' occurred and was caught.</Description>
  <DateTime>2016-03-16 18:04:11Z</DateTime>
  <ExceptionType>System.Data.OracleClient.OracleException, System.Data.OracleClient, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</ExceptionType>
  <Message>ORA-20005: CONTEXTO DE ACESSO INVALIDO
ORA-06512: at "ERESULTS_V2_DEV.PCK_ER_DOCS", line 311
ORA-06512: at "ERESULTS_V2_DEV.PCK_ER_DOCS", line 2431
ORA-06512: at line 1
</Message>
  <Source>System.Data.OracleClient</Source>
  <HelpLink />
  <Property name="Code">20005</Property>
  <Property name="ErrorCode">-2146232008</Property>
  <Property name="Data">System.Collections.ListDictionaryInternal</Property>
  <Property name="TargetSite">Void CheckError(System.Data.OracleClient.OciErrorHandle, Int32)</Property>
  <Property name="HResult">-2146232008</Property>
  <StackTrace>   at System.Data.OracleClient.OracleConnection.CheckError(OciErrorHandle errorHandle, Int32 rc)
   at System.Data.OracleClient.OracleCommand.Execute(OciStatementHandle statementHandle, CommandBehavior behavior, Boolean needRowid, OciRowidDescriptor&amp; rowidDescriptor, ArrayList&amp; resultParameterOrdinals)
   at System.Data.OracleClient.OracleCommand.Execute(OciStatementHandle statementHandle, CommandBehavior behavior, ArrayList&amp; resultParameterOrdinals)
   at System.Data.OracleClient.OracleCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.OracleClient.OracleCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.DoExecuteReader(DbCommand command, CommandBehavior cmdBehavior)
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.ExecuteReader(DbCommand command)
   at Microsoft.Practices.EnterpriseLibrary.Data.Oracle.OracleDatabase.ExecuteReader(DbCommand command)
   at Cpchs.Eresults.Common.WCF.BusinessEntities.DocumentManagementBER.GetDocsDB(String companyDB, String documentRef, String documentExternalId, String entitiesIds, String episodeType, String episodeId, String patientId, String patientType, Nullable`1 episodeStartDate, Nullable`1 episodeEndDate, String institution, String place, String application, String documentType, Nullable`1 executionStartDate, Nullable`1 executionEndDate, Nullable`1 validationStartDate, Nullable`1 validationEndDate, Nullable`1 emissionStartDate, Nullable`1 emissionEndDate, String reqService, String execService, String globalFilters, String docsSession, String servsSession, String username, Nullable`1 pageNumber, Nullable`1 itemsPerPage, String orderField, String orderType, String report, String isPublic, Nullable`1 workspaceId, String filterString, String period, Nullable`1&amp; resultCount) in d:\eResults\16R101\Glintths.Er.WebServices\Data\Glintths.Er.Common.Data\BusinessEntities\Documents\Document\DocumentManagementBER.cs:line 602</StackTrace>
  <additionalInfo>
    <info name="MachineName" value="RPEREIRA" />
    <info name="TimeStamp" value="16/03/2016 18:04:11" />
    <info name="FullName" value="Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=4.1.0.0, Culture=neutral, PublicKeyToken=null" />
    <info name="AppDomainName" value="/LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-14-131026234039496796" />
    <info name="ThreadIdentity" value="" />
    <info name="WindowsIdentity" value="NT AUTHORITY\SYSTEM" />
  </additionalInfo>
</Exception>
Category: General
Priority: 0
EventId: 100
Severity: Error
Title:Enterprise Library Exception Handling
Machine: RPEREIRA
Application Domain: /LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-14-131026234039496796
Process Id: 8204
Process Name: C:\WINDOWS\SysWOW64\inetsrv\w3wp.exe
Win32 Thread Id: 2776
Thread Name: 
Extended Properties: 
----------------------------------------
----------------------------------------
Timestamp: 16/03/2016 18:06:20
Message: <Exception handlingInstanceId="13c4ee9e-9366-4a41-9c35-0d497d62ffab">
  <Description>An exception of type 'System.Data.OracleClient.OracleException' occurred and was caught.</Description>
  <DateTime>2016-03-16 18:06:20Z</DateTime>
  <ExceptionType>System.Data.OracleClient.OracleException, System.Data.OracleClient, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</ExceptionType>
  <Message>ORA-20005: CONTEXTO DE ACESSO INVALIDO
ORA-06512: at "ERESULTS_V2_DEV.PCK_ER_DOCS", line 311
ORA-06512: at "ERESULTS_V2_DEV.PCK_ER_DOCS", line 2431
ORA-06512: at line 1
</Message>
  <Source>System.Data.OracleClient</Source>
  <HelpLink />
  <Property name="Code">20005</Property>
  <Property name="ErrorCode">-2146232008</Property>
  <Property name="Data">System.Collections.ListDictionaryInternal</Property>
  <Property name="TargetSite">Void CheckError(System.Data.OracleClient.OciErrorHandle, Int32)</Property>
  <Property name="HResult">-2146232008</Property>
  <StackTrace>   at System.Data.OracleClient.OracleConnection.CheckError(OciErrorHandle errorHandle, Int32 rc)
   at System.Data.OracleClient.OracleCommand.Execute(OciStatementHandle statementHandle, CommandBehavior behavior, Boolean needRowid, OciRowidDescriptor&amp; rowidDescriptor, ArrayList&amp; resultParameterOrdinals)
   at System.Data.OracleClient.OracleCommand.Execute(OciStatementHandle statementHandle, CommandBehavior behavior, ArrayList&amp; resultParameterOrdinals)
   at System.Data.OracleClient.OracleCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.OracleClient.OracleCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.DoExecuteReader(DbCommand command, CommandBehavior cmdBehavior)
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.ExecuteReader(DbCommand command)
   at Microsoft.Practices.EnterpriseLibrary.Data.Oracle.OracleDatabase.ExecuteReader(DbCommand command)
   at Cpchs.Eresults.Common.WCF.BusinessEntities.DocumentManagementBER.GetDocsDB(String companyDB, String documentRef, String documentExternalId, String entitiesIds, String episodeType, String episodeId, String patientId, String patientType, Nullable`1 episodeStartDate, Nullable`1 episodeEndDate, String institution, String place, String application, String documentType, Nullable`1 executionStartDate, Nullable`1 executionEndDate, Nullable`1 validationStartDate, Nullable`1 validationEndDate, Nullable`1 emissionStartDate, Nullable`1 emissionEndDate, String reqService, String execService, String globalFilters, String docsSession, String servsSession, String username, Nullable`1 pageNumber, Nullable`1 itemsPerPage, String orderField, String orderType, String report, String isPublic, Nullable`1 workspaceId, String filterString, String period, Nullable`1&amp; resultCount) in d:\eResults\16R101\Glintths.Er.WebServices\Data\Glintths.Er.Common.Data\BusinessEntities\Documents\Document\DocumentManagementBER.cs:line 602</StackTrace>
  <additionalInfo>
    <info name="MachineName" value="RPEREIRA" />
    <info name="TimeStamp" value="16/03/2016 18:06:20" />
    <info name="FullName" value="Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=4.1.0.0, Culture=neutral, PublicKeyToken=null" />
    <info name="AppDomainName" value="/LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-14-131026234039496796" />
    <info name="ThreadIdentity" value="" />
    <info name="WindowsIdentity" value="NT AUTHORITY\SYSTEM" />
  </additionalInfo>
</Exception>
Category: General
Priority: 0
EventId: 100
Severity: Error
Title:Enterprise Library Exception Handling
Machine: RPEREIRA
Application Domain: /LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-14-131026234039496796
Process Id: 8204
Process Name: C:\WINDOWS\SysWOW64\inetsrv\w3wp.exe
Win32 Thread Id: 10080
Thread Name: 
Extended Properties: 
----------------------------------------
----------------------------------------
Timestamp: 22/03/2016 10:05:03
Message: <Exception handlingInstanceId="c97cc53d-3815-4111-a490-0b45c5de6d6f">
  <Description>An exception of type 'System.Data.OracleClient.OracleException' occurred and was caught.</Description>
  <DateTime>2016-03-22 10:05:03Z</DateTime>
  <ExceptionType>System.Data.OracleClient.OracleException, System.Data.OracleClient, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</ExceptionType>
  <Message>ORA-01400: cannot insert NULL into ("ERESULTS_V2"."ER_SUBSCRICAO_ALERTA"."PARAMETRO")
ORA-06512: at "ERESULTS_V2_DEV.PCK_DOCUMENTS_MONITORING", line 626
ORA-06512: at line 1
</Message>
  <Source>System.Data.OracleClient</Source>
  <HelpLink />
  <Property name="Code">1400</Property>
  <Property name="ErrorCode">-2146232008</Property>
  <Property name="Data">System.Collections.ListDictionaryInternal</Property>
  <Property name="TargetSite">Void CheckError(System.Data.OracleClient.OciErrorHandle, Int32)</Property>
  <Property name="HResult">-2146232008</Property>
  <StackTrace>   at System.Data.OracleClient.OracleConnection.CheckError(OciErrorHandle errorHandle, Int32 rc)
   at System.Data.OracleClient.OracleCommand.Execute(OciStatementHandle statementHandle, CommandBehavior behavior, Boolean needRowid, OciRowidDescriptor&amp; rowidDescriptor, ArrayList&amp; resultParameterOrdinals)
   at System.Data.OracleClient.OracleCommand.ExecuteNonQueryInternal(Boolean needRowid, OciRowidDescriptor&amp; rowidDescriptor)
   at System.Data.OracleClient.OracleCommand.ExecuteNonQuery()
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.DoExecuteNonQuery(DbCommand command)
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.ExecuteNonQuery(DbCommand command, DbTransaction transaction)
   at Cpchs.Eresults.Common.WCF.BusinessEntities.Generated.MonitoringManagementBER_GEN.InsertAlertSubscriptionDB(String companyDB, DbTransaction transaction, AlertSubscription obj) in d:\eResults\16R101\Glintths.Er.WebServices\Data\Glintths.Er.Common.Data\BusinessEntities\Documents\Monitoring\Generated\MonitoringManagementBER_GEN.cs:line 1020</StackTrace>
  <additionalInfo>
    <info name="MachineName" value="RPEREIRA" />
    <info name="TimeStamp" value="22/03/2016 10:05:03" />
    <info name="FullName" value="Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=4.1.0.0, Culture=neutral, PublicKeyToken=null" />
    <info name="AppDomainName" value="/LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-7-131031146926758075" />
    <info name="ThreadIdentity" value="" />
    <info name="WindowsIdentity" value="NT AUTHORITY\SYSTEM" />
  </additionalInfo>
</Exception>
Category: General
Priority: 0
EventId: 100
Severity: Error
Title:Enterprise Library Exception Handling
Machine: RPEREIRA
Application Domain: /LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-7-131031146926758075
Process Id: 11360
Process Name: C:\WINDOWS\SysWOW64\inetsrv\w3wp.exe
Win32 Thread Id: 14532
Thread Name: 
Extended Properties: 
----------------------------------------
----------------------------------------
Timestamp: 22/03/2016 10:05:03
Message: <Exception handlingInstanceId="d4578e4a-d7ad-4248-b68a-ccb6067b3481">
  <Description>An exception of type 'System.Data.OracleClient.OracleException' occurred and was caught.</Description>
  <DateTime>2016-03-22 10:05:03Z</DateTime>
  <ExceptionType>System.Data.OracleClient.OracleException, System.Data.OracleClient, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</ExceptionType>
  <Message>ORA-01400: cannot insert NULL into ("ERESULTS_V2"."ER_SUBSCRICAO_ALERTA"."PARAMETRO")
ORA-06512: at "ERESULTS_V2_DEV.PCK_DOCUMENTS_MONITORING", line 626
ORA-06512: at line 1
</Message>
  <Source>System.Data.OracleClient</Source>
  <HelpLink />
  <Property name="Code">1400</Property>
  <Property name="ErrorCode">-2146232008</Property>
  <Property name="Data">System.Collections.ListDictionaryInternal</Property>
  <Property name="TargetSite">Void CheckError(System.Data.OracleClient.OciErrorHandle, Int32)</Property>
  <Property name="HResult">-2146232008</Property>
  <StackTrace>   at System.Data.OracleClient.OracleConnection.CheckError(OciErrorHandle errorHandle, Int32 rc)
   at System.Data.OracleClient.OracleCommand.Execute(OciStatementHandle statementHandle, CommandBehavior behavior, Boolean needRowid, OciRowidDescriptor&amp; rowidDescriptor, ArrayList&amp; resultParameterOrdinals)
   at System.Data.OracleClient.OracleCommand.ExecuteNonQueryInternal(Boolean needRowid, OciRowidDescriptor&amp; rowidDescriptor)
   at System.Data.OracleClient.OracleCommand.ExecuteNonQuery()
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.DoExecuteNonQuery(DbCommand command)
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.ExecuteNonQuery(DbCommand command, DbTransaction transaction)
   at Cpchs.Eresults.Common.WCF.BusinessEntities.Generated.MonitoringManagementBER_GEN.InsertAlertSubscriptionDB(String companyDB, DbTransaction transaction, AlertSubscription obj) in d:\eResults\16R101\Glintths.Er.WebServices\Data\Glintths.Er.Common.Data\BusinessEntities\Documents\Monitoring\Generated\MonitoringManagementBER_GEN.cs:line 1039
   at Cpchs.Eresults.Common.WCF.BusinessEntities.Generated.MonitoringManagementBER_GEN.InsertAlertSubscription(String companyDB, AlertSubscription obj, DbTransaction[] transaction) in d:\eResults\16R101\Glintths.Er.WebServices\Data\Glintths.Er.Common.Data\BusinessEntities\Documents\Monitoring\Generated\MonitoringManagementBER_GEN.cs:line 925</StackTrace>
  <additionalInfo>
    <info name="MachineName" value="RPEREIRA" />
    <info name="TimeStamp" value="22/03/2016 10:05:03" />
    <info name="FullName" value="Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=4.1.0.0, Culture=neutral, PublicKeyToken=null" />
    <info name="AppDomainName" value="/LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-7-131031146926758075" />
    <info name="ThreadIdentity" value="" />
    <info name="WindowsIdentity" value="NT AUTHORITY\SYSTEM" />
  </additionalInfo>
</Exception>
Category: General
Priority: 0
EventId: 100
Severity: Error
Title:Enterprise Library Exception Handling
Machine: RPEREIRA
Application Domain: /LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-7-131031146926758075
Process Id: 11360
Process Name: C:\WINDOWS\SysWOW64\inetsrv\w3wp.exe
Win32 Thread Id: 14532
Thread Name: 
Extended Properties: 
----------------------------------------
----------------------------------------
Timestamp: 22/03/2016 10:21:15
Message: <Exception handlingInstanceId="5c847f11-be7d-4bb7-aa3d-ebba7e257b57">
  <Description>An exception of type 'System.Data.OracleClient.OracleException' occurred and was caught.</Description>
  <DateTime>2016-03-22 10:21:15Z</DateTime>
  <ExceptionType>System.Data.OracleClient.OracleException, System.Data.OracleClient, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</ExceptionType>
  <Message>ORA-01400: cannot insert NULL into ("ERESULTS_V2"."ER_SUBSCRICAO_ALERTA"."PARAMETRO")
ORA-06512: at "ERESULTS_V2_DEV.PCK_DOCUMENTS_MONITORING", line 626
ORA-06512: at line 1
</Message>
  <Source>System.Data.OracleClient</Source>
  <HelpLink />
  <Property name="Code">1400</Property>
  <Property name="ErrorCode">-2146232008</Property>
  <Property name="Data">System.Collections.ListDictionaryInternal</Property>
  <Property name="TargetSite">Void CheckError(System.Data.OracleClient.OciErrorHandle, Int32)</Property>
  <Property name="HResult">-2146232008</Property>
  <StackTrace>   at System.Data.OracleClient.OracleConnection.CheckError(OciErrorHandle errorHandle, Int32 rc)
   at System.Data.OracleClient.OracleCommand.Execute(OciStatementHandle statementHandle, CommandBehavior behavior, Boolean needRowid, OciRowidDescriptor&amp; rowidDescriptor, ArrayList&amp; resultParameterOrdinals)
   at System.Data.OracleClient.OracleCommand.ExecuteNonQueryInternal(Boolean needRowid, OciRowidDescriptor&amp; rowidDescriptor)
   at System.Data.OracleClient.OracleCommand.ExecuteNonQuery()
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.DoExecuteNonQuery(DbCommand command)
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.ExecuteNonQuery(DbCommand command, DbTransaction transaction)
   at Cpchs.Eresults.Common.WCF.BusinessEntities.Generated.MonitoringManagementBER_GEN.InsertAlertSubscriptionDB(String companyDB, DbTransaction transaction, AlertSubscription obj) in d:\eResults\16R101\Glintths.Er.WebServices\Data\Glintths.Er.Common.Data\BusinessEntities\Documents\Monitoring\Generated\MonitoringManagementBER_GEN.cs:line 1020</StackTrace>
  <additionalInfo>
    <info name="MachineName" value="RPEREIRA" />
    <info name="TimeStamp" value="22/03/2016 10:21:15" />
    <info name="FullName" value="Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=4.1.0.0, Culture=neutral, PublicKeyToken=null" />
    <info name="AppDomainName" value="/LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-8-131031150665325653" />
    <info name="ThreadIdentity" value="" />
    <info name="WindowsIdentity" value="NT AUTHORITY\SYSTEM" />
  </additionalInfo>
</Exception>
Category: General
Priority: 0
EventId: 100
Severity: Error
Title:Enterprise Library Exception Handling
Machine: RPEREIRA
Application Domain: /LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-8-131031150665325653
Process Id: 11360
Process Name: C:\WINDOWS\SysWOW64\inetsrv\w3wp.exe
Win32 Thread Id: 15236
Thread Name: 
Extended Properties: 
----------------------------------------
----------------------------------------
Timestamp: 22/03/2016 10:21:15
Message: <Exception handlingInstanceId="9225127e-4372-49f0-a85f-56253ee1caff">
  <Description>An exception of type 'System.Data.OracleClient.OracleException' occurred and was caught.</Description>
  <DateTime>2016-03-22 10:21:15Z</DateTime>
  <ExceptionType>System.Data.OracleClient.OracleException, System.Data.OracleClient, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</ExceptionType>
  <Message>ORA-01400: cannot insert NULL into ("ERESULTS_V2"."ER_SUBSCRICAO_ALERTA"."PARAMETRO")
ORA-06512: at "ERESULTS_V2_DEV.PCK_DOCUMENTS_MONITORING", line 626
ORA-06512: at line 1
</Message>
  <Source>System.Data.OracleClient</Source>
  <HelpLink />
  <Property name="Code">1400</Property>
  <Property name="ErrorCode">-2146232008</Property>
  <Property name="Data">System.Collections.ListDictionaryInternal</Property>
  <Property name="TargetSite">Void CheckError(System.Data.OracleClient.OciErrorHandle, Int32)</Property>
  <Property name="HResult">-2146232008</Property>
  <StackTrace>   at System.Data.OracleClient.OracleConnection.CheckError(OciErrorHandle errorHandle, Int32 rc)
   at System.Data.OracleClient.OracleCommand.Execute(OciStatementHandle statementHandle, CommandBehavior behavior, Boolean needRowid, OciRowidDescriptor&amp; rowidDescriptor, ArrayList&amp; resultParameterOrdinals)
   at System.Data.OracleClient.OracleCommand.ExecuteNonQueryInternal(Boolean needRowid, OciRowidDescriptor&amp; rowidDescriptor)
   at System.Data.OracleClient.OracleCommand.ExecuteNonQuery()
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.DoExecuteNonQuery(DbCommand command)
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.ExecuteNonQuery(DbCommand command, DbTransaction transaction)
   at Cpchs.Eresults.Common.WCF.BusinessEntities.Generated.MonitoringManagementBER_GEN.InsertAlertSubscriptionDB(String companyDB, DbTransaction transaction, AlertSubscription obj) in d:\eResults\16R101\Glintths.Er.WebServices\Data\Glintths.Er.Common.Data\BusinessEntities\Documents\Monitoring\Generated\MonitoringManagementBER_GEN.cs:line 1039
   at Cpchs.Eresults.Common.WCF.BusinessEntities.Generated.MonitoringManagementBER_GEN.InsertAlertSubscription(String companyDB, AlertSubscription obj, DbTransaction[] transaction) in d:\eResults\16R101\Glintths.Er.WebServices\Data\Glintths.Er.Common.Data\BusinessEntities\Documents\Monitoring\Generated\MonitoringManagementBER_GEN.cs:line 925</StackTrace>
  <additionalInfo>
    <info name="MachineName" value="RPEREIRA" />
    <info name="TimeStamp" value="22/03/2016 10:21:15" />
    <info name="FullName" value="Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=4.1.0.0, Culture=neutral, PublicKeyToken=null" />
    <info name="AppDomainName" value="/LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-8-131031150665325653" />
    <info name="ThreadIdentity" value="" />
    <info name="WindowsIdentity" value="NT AUTHORITY\SYSTEM" />
  </additionalInfo>
</Exception>
Category: General
Priority: 0
EventId: 100
Severity: Error
Title:Enterprise Library Exception Handling
Machine: RPEREIRA
Application Domain: /LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-8-131031150665325653
Process Id: 11360
Process Name: C:\WINDOWS\SysWOW64\inetsrv\w3wp.exe
Win32 Thread Id: 15236
Thread Name: 
Extended Properties: 
----------------------------------------
----------------------------------------
Timestamp: 22/03/2016 11:40:00
Message: <Exception handlingInstanceId="4c9da477-5809-46ec-97d8-e4d86c53120f">
  <Description>An exception of type 'System.Data.OracleClient.OracleException' occurred and was caught.</Description>
  <DateTime>2016-03-22 11:40:00Z</DateTime>
  <ExceptionType>System.Data.OracleClient.OracleException, System.Data.OracleClient, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</ExceptionType>
  <Message>ORA-06502: PL/SQL: numeric or value error: character string buffer too small
ORA-06512: at "ERESULTS_V2_DEV.PCK_DOCUMENTS_MONITORING", line 274
ORA-06512: at line 1
</Message>
  <Source>System.Data.OracleClient</Source>
  <HelpLink />
  <Property name="Code">6502</Property>
  <Property name="ErrorCode">-2146232008</Property>
  <Property name="Data">System.Collections.ListDictionaryInternal</Property>
  <Property name="TargetSite">Void CheckError(System.Data.OracleClient.OciErrorHandle, Int32)</Property>
  <Property name="HResult">-2146232008</Property>
  <StackTrace>   at System.Data.OracleClient.OracleConnection.CheckError(OciErrorHandle errorHandle, Int32 rc)
   at System.Data.OracleClient.OracleCommand.Execute(OciStatementHandle statementHandle, CommandBehavior behavior, Boolean needRowid, OciRowidDescriptor&amp; rowidDescriptor, ArrayList&amp; resultParameterOrdinals)
   at System.Data.OracleClient.OracleCommand.Execute(OciStatementHandle statementHandle, CommandBehavior behavior, ArrayList&amp; resultParameterOrdinals)
   at System.Data.OracleClient.OracleCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.OracleClient.OracleCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.DoExecuteReader(DbCommand command, CommandBehavior cmdBehavior)
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.ExecuteReader(DbCommand command)
   at Microsoft.Practices.EnterpriseLibrary.Data.Oracle.OracleDatabase.ExecuteReader(DbCommand command)
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.ExecuteReader(String storedProcedureName, Object[] parameterValues)
   at Cpchs.Eresults.Common.WCF.BusinessEntities.Generated.MonitoringManagementBER_GEN.GetDocLogsByMultiCriteriaDB(String companyDB, Nullable`1 patTypeId, String patId, Nullable`1 epiTypeId, String epiId, Nullable`1 instId, Nullable`1 placeId, Nullable`1 appId, Nullable`1 docTypeId, String doc, Nullable`1 docDateBegin, Nullable`1 docDateEnd, Nullable`1 arrivDateBegin, Nullable`1 arrivDateEnd, Nullable`1 procDateBegin, Nullable`1 procDateEnd, Nullable`1 statusId, Nullable`1 alertId, String showHistory, Nullable`1 pageNumber, Nullable`1 itemsPerPage, String orderField, String orderType) in d:\eResults\16R101\Glintths.Er.WebServices\Data\Glintths.Er.Common.Data\BusinessEntities\Documents\Monitoring\Generated\MonitoringManagementBER_GEN.cs:line 115</StackTrace>
  <additionalInfo>
    <info name="MachineName" value="RPEREIRA" />
    <info name="TimeStamp" value="22/03/2016 11:40:00" />
    <info name="FullName" value="Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=4.1.0.0, Culture=neutral, PublicKeyToken=null" />
    <info name="AppDomainName" value="/LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-1-131031203070092564" />
    <info name="ThreadIdentity" value="" />
    <info name="WindowsIdentity" value="NT AUTHORITY\SYSTEM" />
  </additionalInfo>
</Exception>
Category: General
Priority: 0
EventId: 100
Severity: Error
Title:Enterprise Library Exception Handling
Machine: RPEREIRA
Application Domain: /LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-1-131031203070092564
Process Id: 748
Process Name: C:\WINDOWS\SysWOW64\inetsrv\w3wp.exe
Win32 Thread Id: 948
Thread Name: 
Extended Properties: 
----------------------------------------
----------------------------------------
Timestamp: 22/03/2016 11:42:04
Message: <Exception handlingInstanceId="fbd97d92-5b88-4448-b4d8-b488c0fbaa2a">
  <Description>An exception of type 'System.Data.OracleClient.OracleException' occurred and was caught.</Description>
  <DateTime>2016-03-22 11:42:04Z</DateTime>
  <ExceptionType>System.Data.OracleClient.OracleException, System.Data.OracleClient, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</ExceptionType>
  <Message>ORA-06502: PL/SQL: numeric or value error: character string buffer too small
ORA-06512: at "ERESULTS_V2_DEV.PCK_DOCUMENTS_MONITORING", line 274
ORA-06512: at line 1
</Message>
  <Source>System.Data.OracleClient</Source>
  <HelpLink />
  <Property name="Code">6502</Property>
  <Property name="ErrorCode">-2146232008</Property>
  <Property name="Data">System.Collections.ListDictionaryInternal</Property>
  <Property name="TargetSite">Void CheckError(System.Data.OracleClient.OciErrorHandle, Int32)</Property>
  <Property name="HResult">-2146232008</Property>
  <StackTrace>   at System.Data.OracleClient.OracleConnection.CheckError(OciErrorHandle errorHandle, Int32 rc)
   at System.Data.OracleClient.OracleCommand.Execute(OciStatementHandle statementHandle, CommandBehavior behavior, Boolean needRowid, OciRowidDescriptor&amp; rowidDescriptor, ArrayList&amp; resultParameterOrdinals)
   at System.Data.OracleClient.OracleCommand.Execute(OciStatementHandle statementHandle, CommandBehavior behavior, ArrayList&amp; resultParameterOrdinals)
   at System.Data.OracleClient.OracleCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.OracleClient.OracleCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.DoExecuteReader(DbCommand command, CommandBehavior cmdBehavior)
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.ExecuteReader(DbCommand command)
   at Microsoft.Practices.EnterpriseLibrary.Data.Oracle.OracleDatabase.ExecuteReader(DbCommand command)
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.ExecuteReader(String storedProcedureName, Object[] parameterValues)
   at Cpchs.Eresults.Common.WCF.BusinessEntities.Generated.MonitoringManagementBER_GEN.GetDocLogsByMultiCriteriaDB(String companyDB, Nullable`1 patTypeId, String patId, Nullable`1 epiTypeId, String epiId, Nullable`1 instId, Nullable`1 placeId, Nullable`1 appId, Nullable`1 docTypeId, String doc, Nullable`1 docDateBegin, Nullable`1 docDateEnd, Nullable`1 arrivDateBegin, Nullable`1 arrivDateEnd, Nullable`1 procDateBegin, Nullable`1 procDateEnd, Nullable`1 statusId, Nullable`1 alertId, String showHistory, Nullable`1 pageNumber, Nullable`1 itemsPerPage, String orderField, String orderType) in d:\eResults\16R101\Glintths.Er.WebServices\Data\Glintths.Er.Common.Data\BusinessEntities\Documents\Monitoring\Generated\MonitoringManagementBER_GEN.cs:line 115</StackTrace>
  <additionalInfo>
    <info name="MachineName" value="RPEREIRA" />
    <info name="TimeStamp" value="22/03/2016 11:42:04" />
    <info name="FullName" value="Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=4.1.0.0, Culture=neutral, PublicKeyToken=null" />
    <info name="AppDomainName" value="/LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-1-131031203070092564" />
    <info name="ThreadIdentity" value="" />
    <info name="WindowsIdentity" value="NT AUTHORITY\SYSTEM" />
  </additionalInfo>
</Exception>
Category: General
Priority: 0
EventId: 100
Severity: Error
Title:Enterprise Library Exception Handling
Machine: RPEREIRA
Application Domain: /LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-1-131031203070092564
Process Id: 748
Process Name: C:\WINDOWS\SysWOW64\inetsrv\w3wp.exe
Win32 Thread Id: 948
Thread Name: 
Extended Properties: 
----------------------------------------
----------------------------------------
Timestamp: 22/03/2016 11:46:56
Message: <Exception handlingInstanceId="d703199c-489f-4a68-8dd6-67511d7ab558">
  <Description>An exception of type 'System.Data.OracleClient.OracleException' occurred and was caught.</Description>
  <DateTime>2016-03-22 11:46:56Z</DateTime>
  <ExceptionType>System.Data.OracleClient.OracleException, System.Data.OracleClient, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</ExceptionType>
  <Message>ORA-06502: PL/SQL: numeric or value error: character string buffer too small
ORA-06512: at "ERESULTS_V2_DEV.PCK_DOCUMENTS_MONITORING", line 274
ORA-06512: at line 1
</Message>
  <Source>System.Data.OracleClient</Source>
  <HelpLink />
  <Property name="Code">6502</Property>
  <Property name="ErrorCode">-2146232008</Property>
  <Property name="Data">System.Collections.ListDictionaryInternal</Property>
  <Property name="TargetSite">Void CheckError(System.Data.OracleClient.OciErrorHandle, Int32)</Property>
  <Property name="HResult">-2146232008</Property>
  <StackTrace>   at System.Data.OracleClient.OracleConnection.CheckError(OciErrorHandle errorHandle, Int32 rc)
   at System.Data.OracleClient.OracleCommand.Execute(OciStatementHandle statementHandle, CommandBehavior behavior, Boolean needRowid, OciRowidDescriptor&amp; rowidDescriptor, ArrayList&amp; resultParameterOrdinals)
   at System.Data.OracleClient.OracleCommand.Execute(OciStatementHandle statementHandle, CommandBehavior behavior, ArrayList&amp; resultParameterOrdinals)
   at System.Data.OracleClient.OracleCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.OracleClient.OracleCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.DoExecuteReader(DbCommand command, CommandBehavior cmdBehavior)
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.ExecuteReader(DbCommand command)
   at Microsoft.Practices.EnterpriseLibrary.Data.Oracle.OracleDatabase.ExecuteReader(DbCommand command)
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.ExecuteReader(String storedProcedureName, Object[] parameterValues)
   at Cpchs.Eresults.Common.WCF.BusinessEntities.Generated.MonitoringManagementBER_GEN.GetDocLogsByMultiCriteriaDB(String companyDB, Nullable`1 patTypeId, String patId, Nullable`1 epiTypeId, String epiId, Nullable`1 instId, Nullable`1 placeId, Nullable`1 appId, Nullable`1 docTypeId, String doc, Nullable`1 docDateBegin, Nullable`1 docDateEnd, Nullable`1 arrivDateBegin, Nullable`1 arrivDateEnd, Nullable`1 procDateBegin, Nullable`1 procDateEnd, Nullable`1 statusId, Nullable`1 alertId, String showHistory, Nullable`1 pageNumber, Nullable`1 itemsPerPage, String orderField, String orderType) in d:\eResults\16R101\Glintths.Er.WebServices\Data\Glintths.Er.Common.Data\BusinessEntities\Documents\Monitoring\Generated\MonitoringManagementBER_GEN.cs:line 115</StackTrace>
  <additionalInfo>
    <info name="MachineName" value="RPEREIRA" />
    <info name="TimeStamp" value="22/03/2016 11:46:56" />
    <info name="FullName" value="Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=4.1.0.0, Culture=neutral, PublicKeyToken=null" />
    <info name="AppDomainName" value="/LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-1-131031203070092564" />
    <info name="ThreadIdentity" value="" />
    <info name="WindowsIdentity" value="NT AUTHORITY\SYSTEM" />
  </additionalInfo>
</Exception>
Category: General
Priority: 0
EventId: 100
Severity: Error
Title:Enterprise Library Exception Handling
Machine: RPEREIRA
Application Domain: /LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-1-131031203070092564
Process Id: 748
Process Name: C:\WINDOWS\SysWOW64\inetsrv\w3wp.exe
Win32 Thread Id: 948
Thread Name: 
Extended Properties: 
----------------------------------------
----------------------------------------
Timestamp: 22/03/2016 11:47:38
Message: <Exception handlingInstanceId="f328dc46-2f49-4ec1-825b-9aabfc77f1fe">
  <Description>An exception of type 'System.Data.OracleClient.OracleException' occurred and was caught.</Description>
  <DateTime>2016-03-22 11:47:38Z</DateTime>
  <ExceptionType>System.Data.OracleClient.OracleException, System.Data.OracleClient, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</ExceptionType>
  <Message>ORA-06502: PL/SQL: numeric or value error: character string buffer too small
ORA-06512: at "ERESULTS_V2_DEV.PCK_DOCUMENTS_MONITORING", line 274
ORA-06512: at line 1
</Message>
  <Source>System.Data.OracleClient</Source>
  <HelpLink />
  <Property name="Code">6502</Property>
  <Property name="ErrorCode">-2146232008</Property>
  <Property name="Data">System.Collections.ListDictionaryInternal</Property>
  <Property name="TargetSite">Void CheckError(System.Data.OracleClient.OciErrorHandle, Int32)</Property>
  <Property name="HResult">-2146232008</Property>
  <StackTrace>   at System.Data.OracleClient.OracleConnection.CheckError(OciErrorHandle errorHandle, Int32 rc)
   at System.Data.OracleClient.OracleCommand.Execute(OciStatementHandle statementHandle, CommandBehavior behavior, Boolean needRowid, OciRowidDescriptor&amp; rowidDescriptor, ArrayList&amp; resultParameterOrdinals)
   at System.Data.OracleClient.OracleCommand.Execute(OciStatementHandle statementHandle, CommandBehavior behavior, ArrayList&amp; resultParameterOrdinals)
   at System.Data.OracleClient.OracleCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.OracleClient.OracleCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.DoExecuteReader(DbCommand command, CommandBehavior cmdBehavior)
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.ExecuteReader(DbCommand command)
   at Microsoft.Practices.EnterpriseLibrary.Data.Oracle.OracleDatabase.ExecuteReader(DbCommand command)
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.ExecuteReader(String storedProcedureName, Object[] parameterValues)
   at Cpchs.Eresults.Common.WCF.BusinessEntities.Generated.MonitoringManagementBER_GEN.GetDocLogsByMultiCriteriaDB(String companyDB, Nullable`1 patTypeId, String patId, Nullable`1 epiTypeId, String epiId, Nullable`1 instId, Nullable`1 placeId, Nullable`1 appId, Nullable`1 docTypeId, String doc, Nullable`1 docDateBegin, Nullable`1 docDateEnd, Nullable`1 arrivDateBegin, Nullable`1 arrivDateEnd, Nullable`1 procDateBegin, Nullable`1 procDateEnd, Nullable`1 statusId, Nullable`1 alertId, String showHistory, Nullable`1 pageNumber, Nullable`1 itemsPerPage, String orderField, String orderType) in d:\eResults\16R101\Glintths.Er.WebServices\Data\Glintths.Er.Common.Data\BusinessEntities\Documents\Monitoring\Generated\MonitoringManagementBER_GEN.cs:line 115</StackTrace>
  <additionalInfo>
    <info name="MachineName" value="RPEREIRA" />
    <info name="TimeStamp" value="22/03/2016 11:47:38" />
    <info name="FullName" value="Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=4.1.0.0, Culture=neutral, PublicKeyToken=null" />
    <info name="AppDomainName" value="/LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-1-131031203070092564" />
    <info name="ThreadIdentity" value="" />
    <info name="WindowsIdentity" value="NT AUTHORITY\SYSTEM" />
  </additionalInfo>
</Exception>
Category: General
Priority: 0
EventId: 100
Severity: Error
Title:Enterprise Library Exception Handling
Machine: RPEREIRA
Application Domain: /LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-1-131031203070092564
Process Id: 748
Process Name: C:\WINDOWS\SysWOW64\inetsrv\w3wp.exe
Win32 Thread Id: 948
Thread Name: 
Extended Properties: 
----------------------------------------
----------------------------------------
Timestamp: 22/03/2016 11:48:46
Message: <Exception handlingInstanceId="c76bc3f6-7f9f-47b6-bafc-d59ff10b7ed9">
  <Description>An exception of type 'System.Data.OracleClient.OracleException' occurred and was caught.</Description>
  <DateTime>2016-03-22 11:48:46Z</DateTime>
  <ExceptionType>System.Data.OracleClient.OracleException, System.Data.OracleClient, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</ExceptionType>
  <Message>ORA-01403: no data found
ORA-06512: at "ERESULTS_V2_DEV.PCK_ER2INDEXER_V3", line 1697
ORA-06512: at "ERESULTS_V2_DEV.PCK_DOCUMENTS_MONITORING", line 371
ORA-06512: at line 1
</Message>
  <Source>System.Data.OracleClient</Source>
  <HelpLink />
  <Property name="Code">1403</Property>
  <Property name="ErrorCode">-2146232008</Property>
  <Property name="Data">System.Collections.ListDictionaryInternal</Property>
  <Property name="TargetSite">Void CheckError(System.Data.OracleClient.OciErrorHandle, Int32)</Property>
  <Property name="HResult">-2146232008</Property>
  <StackTrace>   at System.Data.OracleClient.OracleConnection.CheckError(OciErrorHandle errorHandle, Int32 rc)
   at System.Data.OracleClient.OracleCommand.Execute(OciStatementHandle statementHandle, CommandBehavior behavior, Boolean needRowid, OciRowidDescriptor&amp; rowidDescriptor, ArrayList&amp; resultParameterOrdinals)
   at System.Data.OracleClient.OracleCommand.ExecuteNonQueryInternal(Boolean needRowid, OciRowidDescriptor&amp; rowidDescriptor)
   at System.Data.OracleClient.OracleCommand.ExecuteNonQuery()
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.DoExecuteNonQuery(DbCommand command)
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.ExecuteNonQuery(DbCommand command)
   at Cpchs.Eresults.Common.WCF.BusinessEntities.Generated.MonitoringManagementBER_GEN.ProcessIndexDocumentDB(String companyDB, DbTransaction transaction, DocumentLog obj) in d:\eResults\16R101\Glintths.Er.WebServices\Data\Glintths.Er.Common.Data\BusinessEntities\Documents\Monitoring\Generated\MonitoringManagementBER_GEN.cs:line 224</StackTrace>
  <additionalInfo>
    <info name="MachineName" value="RPEREIRA" />
    <info name="TimeStamp" value="22/03/2016 11:48:46" />
    <info name="FullName" value="Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=4.1.0.0, Culture=neutral, PublicKeyToken=null" />
    <info name="AppDomainName" value="/LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-1-131031203070092564" />
    <info name="ThreadIdentity" value="" />
    <info name="WindowsIdentity" value="NT AUTHORITY\SYSTEM" />
  </additionalInfo>
</Exception>
Category: General
Priority: 0
EventId: 100
Severity: Error
Title:Enterprise Library Exception Handling
Machine: RPEREIRA
Application Domain: /LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-1-131031203070092564
Process Id: 748
Process Name: C:\WINDOWS\SysWOW64\inetsrv\w3wp.exe
Win32 Thread Id: 20132
Thread Name: 
Extended Properties: 
----------------------------------------
----------------------------------------
Timestamp: 22/03/2016 11:48:46
Message: <Exception handlingInstanceId="e644c042-5039-4cdc-bf09-9877dc6f0d7a">
  <Description>An exception of type 'System.Data.OracleClient.OracleException' occurred and was caught.</Description>
  <DateTime>2016-03-22 11:48:46Z</DateTime>
  <ExceptionType>System.Data.OracleClient.OracleException, System.Data.OracleClient, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</ExceptionType>
  <Message>ORA-01403: no data found
ORA-06512: at "ERESULTS_V2_DEV.PCK_ER2INDEXER_V3", line 1697
ORA-06512: at "ERESULTS_V2_DEV.PCK_DOCUMENTS_MONITORING", line 371
ORA-06512: at line 1
</Message>
  <Source>System.Data.OracleClient</Source>
  <HelpLink />
  <Property name="Code">1403</Property>
  <Property name="ErrorCode">-2146232008</Property>
  <Property name="Data">System.Collections.ListDictionaryInternal</Property>
  <Property name="TargetSite">Void CheckError(System.Data.OracleClient.OciErrorHandle, Int32)</Property>
  <Property name="HResult">-2146232008</Property>
  <StackTrace>   at System.Data.OracleClient.OracleConnection.CheckError(OciErrorHandle errorHandle, Int32 rc)
   at System.Data.OracleClient.OracleCommand.Execute(OciStatementHandle statementHandle, CommandBehavior behavior, Boolean needRowid, OciRowidDescriptor&amp; rowidDescriptor, ArrayList&amp; resultParameterOrdinals)
   at System.Data.OracleClient.OracleCommand.ExecuteNonQueryInternal(Boolean needRowid, OciRowidDescriptor&amp; rowidDescriptor)
   at System.Data.OracleClient.OracleCommand.ExecuteNonQuery()
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.DoExecuteNonQuery(DbCommand command)
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.ExecuteNonQuery(DbCommand command)
   at Cpchs.Eresults.Common.WCF.BusinessEntities.Generated.MonitoringManagementBER_GEN.ProcessIndexDocumentDB(String companyDB, DbTransaction transaction, DocumentLog obj) in d:\eResults\16R101\Glintths.Er.WebServices\Data\Glintths.Er.Common.Data\BusinessEntities\Documents\Monitoring\Generated\MonitoringManagementBER_GEN.cs:line 238
   at Cpchs.Eresults.Common.WCF.BusinessEntities.Generated.MonitoringManagementBER_GEN.ProcessIndexDocument(String companyDB, DocumentLog obj, DbTransaction[] transaction) in d:\eResults\16R101\Glintths.Er.WebServices\Data\Glintths.Er.Common.Data\BusinessEntities\Documents\Monitoring\Generated\MonitoringManagementBER_GEN.cs:line 148</StackTrace>
  <additionalInfo>
    <info name="MachineName" value="RPEREIRA" />
    <info name="TimeStamp" value="22/03/2016 11:48:46" />
    <info name="FullName" value="Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=4.1.0.0, Culture=neutral, PublicKeyToken=null" />
    <info name="AppDomainName" value="/LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-1-131031203070092564" />
    <info name="ThreadIdentity" value="" />
    <info name="WindowsIdentity" value="NT AUTHORITY\SYSTEM" />
  </additionalInfo>
</Exception>
Category: General
Priority: 0
EventId: 100
Severity: Error
Title:Enterprise Library Exception Handling
Machine: RPEREIRA
Application Domain: /LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-1-131031203070092564
Process Id: 748
Process Name: C:\WINDOWS\SysWOW64\inetsrv\w3wp.exe
Win32 Thread Id: 20132
Thread Name: 
Extended Properties: 
----------------------------------------
----------------------------------------
Timestamp: 22/03/2016 14:11:26
Message: <Exception handlingInstanceId="69c9c102-6418-4ffa-955f-e017803bc017">
  <Description>An exception of type 'System.Data.DBConcurrencyException' occurred and was caught.</Description>
  <DateTime>2016-03-22 14:11:26Z</DateTime>
  <ExceptionType>System.Data.DBConcurrencyException, System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</ExceptionType>
  <Message>DB concurrency violation.</Message>
  <Source>Glintths.Er.Common.Data</Source>
  <HelpLink />
  <Property name="Row">&lt;undefined value&gt;</Property>
  <Property name="RowCount">0</Property>
  <Property name="Data">System.Collections.ListDictionaryInternal</Property>
  <Property name="TargetSite">Void DeleteAlertSubscriptionDB(System.String, System.Data.Common.DbTransaction, Cpchs.Eresults.Common.WCF.BusinessEntities.AlertSubscription)</Property>
  <Property name="HResult">-2146232011</Property>
  <StackTrace>   at Cpchs.Eresults.Common.WCF.BusinessEntities.Generated.MonitoringManagementBER_GEN.DeleteAlertSubscriptionDB(String companyDB, DbTransaction transaction, AlertSubscription obj) in d:\eResults\16R101\Glintths.Er.WebServices\Data\Glintths.Er.Common.Data\BusinessEntities\Documents\Monitoring\Generated\MonitoringManagementBER_GEN.cs:line 1253</StackTrace>
  <additionalInfo>
    <info name="MachineName" value="RPEREIRA" />
    <info name="TimeStamp" value="22/03/2016 14:11:26" />
    <info name="FullName" value="Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=4.1.0.0, Culture=neutral, PublicKeyToken=null" />
    <info name="AppDomainName" value="/LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-23-131031294861537603" />
    <info name="ThreadIdentity" value="" />
    <info name="WindowsIdentity" value="NT AUTHORITY\SYSTEM" />
  </additionalInfo>
</Exception>
Category: General
Priority: 0
EventId: 100
Severity: Error
Title:Enterprise Library Exception Handling
Machine: RPEREIRA
Application Domain: /LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-23-131031294861537603
Process Id: 748
Process Name: C:\WINDOWS\SysWOW64\inetsrv\w3wp.exe
Win32 Thread Id: 14224
Thread Name: 
Extended Properties: 
----------------------------------------
----------------------------------------
Timestamp: 22/03/2016 14:11:26
Message: <Exception handlingInstanceId="d4e8c446-c38e-406c-b5dc-a9305c59a775">
  <Description>An exception of type 'System.Data.DBConcurrencyException' occurred and was caught.</Description>
  <DateTime>2016-03-22 14:11:26Z</DateTime>
  <ExceptionType>System.Data.DBConcurrencyException, System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</ExceptionType>
  <Message>DB concurrency violation.</Message>
  <Source>Glintths.Er.Common.Data</Source>
  <HelpLink />
  <Property name="Row">&lt;undefined value&gt;</Property>
  <Property name="RowCount">0</Property>
  <Property name="Data">System.Collections.ListDictionaryInternal</Property>
  <Property name="TargetSite">Void DeleteAlertSubscriptionDB(System.String, System.Data.Common.DbTransaction, Cpchs.Eresults.Common.WCF.BusinessEntities.AlertSubscription)</Property>
  <Property name="HResult">-2146232011</Property>
  <StackTrace>   at Cpchs.Eresults.Common.WCF.BusinessEntities.Generated.MonitoringManagementBER_GEN.DeleteAlertSubscriptionDB(String companyDB, DbTransaction transaction, AlertSubscription obj) in d:\eResults\16R101\Glintths.Er.WebServices\Data\Glintths.Er.Common.Data\BusinessEntities\Documents\Monitoring\Generated\MonitoringManagementBER_GEN.cs:line 1263
   at Cpchs.Eresults.Common.WCF.BusinessEntities.Generated.MonitoringManagementBER_GEN.DeleteAlertSubscription(String companyDB, AlertSubscription obj, DbTransaction[] transaction) in d:\eResults\16R101\Glintths.Er.WebServices\Data\Glintths.Er.Common.Data\BusinessEntities\Documents\Monitoring\Generated\MonitoringManagementBER_GEN.cs:line 1195</StackTrace>
  <additionalInfo>
    <info name="MachineName" value="RPEREIRA" />
    <info name="TimeStamp" value="22/03/2016 14:11:26" />
    <info name="FullName" value="Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=4.1.0.0, Culture=neutral, PublicKeyToken=null" />
    <info name="AppDomainName" value="/LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-23-131031294861537603" />
    <info name="ThreadIdentity" value="" />
    <info name="WindowsIdentity" value="NT AUTHORITY\SYSTEM" />
  </additionalInfo>
</Exception>
Category: General
Priority: 0
EventId: 100
Severity: Error
Title:Enterprise Library Exception Handling
Machine: RPEREIRA
Application Domain: /LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-23-131031294861537603
Process Id: 748
Process Name: C:\WINDOWS\SysWOW64\inetsrv\w3wp.exe
Win32 Thread Id: 14224
Thread Name: 
Extended Properties: 
----------------------------------------
----------------------------------------
Timestamp: 22/03/2016 14:14:18
Message: <Exception handlingInstanceId="ba4d82d1-dc0d-4899-bb75-18a627133e45">
  <Description>An exception of type 'System.Data.DBConcurrencyException' occurred and was caught.</Description>
  <DateTime>2016-03-22 14:14:18Z</DateTime>
  <ExceptionType>System.Data.DBConcurrencyException, System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</ExceptionType>
  <Message>DB concurrency violation.</Message>
  <Source>Glintths.Er.Common.Data</Source>
  <HelpLink />
  <Property name="Row">&lt;undefined value&gt;</Property>
  <Property name="RowCount">0</Property>
  <Property name="Data">System.Collections.ListDictionaryInternal</Property>
  <Property name="TargetSite">Void DeleteAlertSubscriptionDB(System.String, System.Data.Common.DbTransaction, Cpchs.Eresults.Common.WCF.BusinessEntities.AlertSubscription)</Property>
  <Property name="HResult">-2146232011</Property>
  <StackTrace>   at Cpchs.Eresults.Common.WCF.BusinessEntities.Generated.MonitoringManagementBER_GEN.DeleteAlertSubscriptionDB(String companyDB, DbTransaction transaction, AlertSubscription obj) in d:\eResults\16R101\Glintths.Er.WebServices\Data\Glintths.Er.Common.Data\BusinessEntities\Documents\Monitoring\Generated\MonitoringManagementBER_GEN.cs:line 1253</StackTrace>
  <additionalInfo>
    <info name="MachineName" value="RPEREIRA" />
    <info name="TimeStamp" value="22/03/2016 14:14:18" />
    <info name="FullName" value="Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=4.1.0.0, Culture=neutral, PublicKeyToken=null" />
    <info name="AppDomainName" value="/LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-23-131031294861537603" />
    <info name="ThreadIdentity" value="" />
    <info name="WindowsIdentity" value="NT AUTHORITY\SYSTEM" />
  </additionalInfo>
</Exception>
Category: General
Priority: 0
EventId: 100
Severity: Error
Title:Enterprise Library Exception Handling
Machine: RPEREIRA
Application Domain: /LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-23-131031294861537603
Process Id: 748
Process Name: C:\WINDOWS\SysWOW64\inetsrv\w3wp.exe
Win32 Thread Id: 20132
Thread Name: 
Extended Properties: 
----------------------------------------
----------------------------------------
Timestamp: 22/03/2016 14:14:18
Message: <Exception handlingInstanceId="16d09b65-5a17-41f6-9573-9e9522cfa994">
  <Description>An exception of type 'System.Data.DBConcurrencyException' occurred and was caught.</Description>
  <DateTime>2016-03-22 14:14:18Z</DateTime>
  <ExceptionType>System.Data.DBConcurrencyException, System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</ExceptionType>
  <Message>DB concurrency violation.</Message>
  <Source>Glintths.Er.Common.Data</Source>
  <HelpLink />
  <Property name="Row">&lt;undefined value&gt;</Property>
  <Property name="RowCount">0</Property>
  <Property name="Data">System.Collections.ListDictionaryInternal</Property>
  <Property name="TargetSite">Void DeleteAlertSubscriptionDB(System.String, System.Data.Common.DbTransaction, Cpchs.Eresults.Common.WCF.BusinessEntities.AlertSubscription)</Property>
  <Property name="HResult">-2146232011</Property>
  <StackTrace>   at Cpchs.Eresults.Common.WCF.BusinessEntities.Generated.MonitoringManagementBER_GEN.DeleteAlertSubscriptionDB(String companyDB, DbTransaction transaction, AlertSubscription obj) in d:\eResults\16R101\Glintths.Er.WebServices\Data\Glintths.Er.Common.Data\BusinessEntities\Documents\Monitoring\Generated\MonitoringManagementBER_GEN.cs:line 1263
   at Cpchs.Eresults.Common.WCF.BusinessEntities.Generated.MonitoringManagementBER_GEN.DeleteAlertSubscription(String companyDB, AlertSubscription obj, DbTransaction[] transaction) in d:\eResults\16R101\Glintths.Er.WebServices\Data\Glintths.Er.Common.Data\BusinessEntities\Documents\Monitoring\Generated\MonitoringManagementBER_GEN.cs:line 1195</StackTrace>
  <additionalInfo>
    <info name="MachineName" value="RPEREIRA" />
    <info name="TimeStamp" value="22/03/2016 14:14:18" />
    <info name="FullName" value="Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=4.1.0.0, Culture=neutral, PublicKeyToken=null" />
    <info name="AppDomainName" value="/LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-23-131031294861537603" />
    <info name="ThreadIdentity" value="" />
    <info name="WindowsIdentity" value="NT AUTHORITY\SYSTEM" />
  </additionalInfo>
</Exception>
Category: General
Priority: 0
EventId: 100
Severity: Error
Title:Enterprise Library Exception Handling
Machine: RPEREIRA
Application Domain: /LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-23-131031294861537603
Process Id: 748
Process Name: C:\WINDOWS\SysWOW64\inetsrv\w3wp.exe
Win32 Thread Id: 20132
Thread Name: 
Extended Properties: 
----------------------------------------
----------------------------------------
Timestamp: 22/03/2016 14:15:16
Message: <Exception handlingInstanceId="a07f4f96-20f7-4edc-bc0c-dd1963d0f689">
  <Description>An exception of type 'System.Data.DBConcurrencyException' occurred and was caught.</Description>
  <DateTime>2016-03-22 14:15:16Z</DateTime>
  <ExceptionType>System.Data.DBConcurrencyException, System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</ExceptionType>
  <Message>DB concurrency violation.</Message>
  <Source>Glintths.Er.Common.Data</Source>
  <HelpLink />
  <Property name="Row">&lt;undefined value&gt;</Property>
  <Property name="RowCount">0</Property>
  <Property name="Data">System.Collections.ListDictionaryInternal</Property>
  <Property name="TargetSite">Void DeleteAlertSubscriptionDB(System.String, System.Data.Common.DbTransaction, Cpchs.Eresults.Common.WCF.BusinessEntities.AlertSubscription)</Property>
  <Property name="HResult">-2146232011</Property>
  <StackTrace>   at Cpchs.Eresults.Common.WCF.BusinessEntities.Generated.MonitoringManagementBER_GEN.DeleteAlertSubscriptionDB(String companyDB, DbTransaction transaction, AlertSubscription obj) in d:\eResults\16R101\Glintths.Er.WebServices\Data\Glintths.Er.Common.Data\BusinessEntities\Documents\Monitoring\Generated\MonitoringManagementBER_GEN.cs:line 1253</StackTrace>
  <additionalInfo>
    <info name="MachineName" value="RPEREIRA" />
    <info name="TimeStamp" value="22/03/2016 14:15:16" />
    <info name="FullName" value="Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=4.1.0.0, Culture=neutral, PublicKeyToken=null" />
    <info name="AppDomainName" value="/LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-23-131031294861537603" />
    <info name="ThreadIdentity" value="" />
    <info name="WindowsIdentity" value="NT AUTHORITY\SYSTEM" />
  </additionalInfo>
</Exception>
Category: General
Priority: 0
EventId: 100
Severity: Error
Title:Enterprise Library Exception Handling
Machine: RPEREIRA
Application Domain: /LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-23-131031294861537603
Process Id: 748
Process Name: C:\WINDOWS\SysWOW64\inetsrv\w3wp.exe
Win32 Thread Id: 20132
Thread Name: 
Extended Properties: 
----------------------------------------
----------------------------------------
Timestamp: 22/03/2016 14:15:16
Message: <Exception handlingInstanceId="417fdd10-3c32-4f5a-b7a0-49fa977ac0d9">
  <Description>An exception of type 'System.Data.DBConcurrencyException' occurred and was caught.</Description>
  <DateTime>2016-03-22 14:15:16Z</DateTime>
  <ExceptionType>System.Data.DBConcurrencyException, System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</ExceptionType>
  <Message>DB concurrency violation.</Message>
  <Source>Glintths.Er.Common.Data</Source>
  <HelpLink />
  <Property name="Row">&lt;undefined value&gt;</Property>
  <Property name="RowCount">0</Property>
  <Property name="Data">System.Collections.ListDictionaryInternal</Property>
  <Property name="TargetSite">Void DeleteAlertSubscriptionDB(System.String, System.Data.Common.DbTransaction, Cpchs.Eresults.Common.WCF.BusinessEntities.AlertSubscription)</Property>
  <Property name="HResult">-2146232011</Property>
  <StackTrace>   at Cpchs.Eresults.Common.WCF.BusinessEntities.Generated.MonitoringManagementBER_GEN.DeleteAlertSubscriptionDB(String companyDB, DbTransaction transaction, AlertSubscription obj) in d:\eResults\16R101\Glintths.Er.WebServices\Data\Glintths.Er.Common.Data\BusinessEntities\Documents\Monitoring\Generated\MonitoringManagementBER_GEN.cs:line 1263
   at Cpchs.Eresults.Common.WCF.BusinessEntities.Generated.MonitoringManagementBER_GEN.DeleteAlertSubscription(String companyDB, AlertSubscription obj, DbTransaction[] transaction) in d:\eResults\16R101\Glintths.Er.WebServices\Data\Glintths.Er.Common.Data\BusinessEntities\Documents\Monitoring\Generated\MonitoringManagementBER_GEN.cs:line 1195</StackTrace>
  <additionalInfo>
    <info name="MachineName" value="RPEREIRA" />
    <info name="TimeStamp" value="22/03/2016 14:15:16" />
    <info name="FullName" value="Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=4.1.0.0, Culture=neutral, PublicKeyToken=null" />
    <info name="AppDomainName" value="/LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-23-131031294861537603" />
    <info name="ThreadIdentity" value="" />
    <info name="WindowsIdentity" value="NT AUTHORITY\SYSTEM" />
  </additionalInfo>
</Exception>
Category: General
Priority: 0
EventId: 100
Severity: Error
Title:Enterprise Library Exception Handling
Machine: RPEREIRA
Application Domain: /LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-23-131031294861537603
Process Id: 748
Process Name: C:\WINDOWS\SysWOW64\inetsrv\w3wp.exe
Win32 Thread Id: 20132
Thread Name: 
Extended Properties: 
----------------------------------------
----------------------------------------
Timestamp: 22/03/2016 14:20:39
Message: <Exception handlingInstanceId="08c9efd5-d475-4646-81d0-13a54f1a6a62">
  <Description>An exception of type 'System.Data.DBConcurrencyException' occurred and was caught.</Description>
  <DateTime>2016-03-22 14:20:39Z</DateTime>
  <ExceptionType>System.Data.DBConcurrencyException, System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</ExceptionType>
  <Message>DB concurrency violation.</Message>
  <Source>Glintths.Er.Common.Data</Source>
  <HelpLink />
  <Property name="Row">&lt;undefined value&gt;</Property>
  <Property name="RowCount">0</Property>
  <Property name="Data">System.Collections.ListDictionaryInternal</Property>
  <Property name="TargetSite">Void DeleteAlertSubscriptionDB(System.String, System.Data.Common.DbTransaction, Cpchs.Eresults.Common.WCF.BusinessEntities.AlertSubscription)</Property>
  <Property name="HResult">-2146232011</Property>
  <StackTrace>   at Cpchs.Eresults.Common.WCF.BusinessEntities.Generated.MonitoringManagementBER_GEN.DeleteAlertSubscriptionDB(String companyDB, DbTransaction transaction, AlertSubscription obj) in d:\eResults\16R101\Glintths.Er.WebServices\Data\Glintths.Er.Common.Data\BusinessEntities\Documents\Monitoring\Generated\MonitoringManagementBER_GEN.cs:line 1253</StackTrace>
  <additionalInfo>
    <info name="MachineName" value="RPEREIRA" />
    <info name="TimeStamp" value="22/03/2016 14:20:39" />
    <info name="FullName" value="Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=4.1.0.0, Culture=neutral, PublicKeyToken=null" />
    <info name="AppDomainName" value="/LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-24-131031300376866978" />
    <info name="ThreadIdentity" value="" />
    <info name="WindowsIdentity" value="NT AUTHORITY\SYSTEM" />
  </additionalInfo>
</Exception>
Category: General
Priority: 0
EventId: 100
Severity: Error
Title:Enterprise Library Exception Handling
Machine: RPEREIRA
Application Domain: /LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-24-131031300376866978
Process Id: 748
Process Name: C:\WINDOWS\SysWOW64\inetsrv\w3wp.exe
Win32 Thread Id: 20132
Thread Name: 
Extended Properties: 
----------------------------------------
----------------------------------------
Timestamp: 22/03/2016 14:20:39
Message: <Exception handlingInstanceId="b9383645-1e23-4180-ab5e-5c347af927e9">
  <Description>An exception of type 'System.Data.DBConcurrencyException' occurred and was caught.</Description>
  <DateTime>2016-03-22 14:20:39Z</DateTime>
  <ExceptionType>System.Data.DBConcurrencyException, System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</ExceptionType>
  <Message>DB concurrency violation.</Message>
  <Source>Glintths.Er.Common.Data</Source>
  <HelpLink />
  <Property name="Row">&lt;undefined value&gt;</Property>
  <Property name="RowCount">0</Property>
  <Property name="Data">System.Collections.ListDictionaryInternal</Property>
  <Property name="TargetSite">Void DeleteAlertSubscriptionDB(System.String, System.Data.Common.DbTransaction, Cpchs.Eresults.Common.WCF.BusinessEntities.AlertSubscription)</Property>
  <Property name="HResult">-2146232011</Property>
  <StackTrace>   at Cpchs.Eresults.Common.WCF.BusinessEntities.Generated.MonitoringManagementBER_GEN.DeleteAlertSubscriptionDB(String companyDB, DbTransaction transaction, AlertSubscription obj) in d:\eResults\16R101\Glintths.Er.WebServices\Data\Glintths.Er.Common.Data\BusinessEntities\Documents\Monitoring\Generated\MonitoringManagementBER_GEN.cs:line 1263
   at Cpchs.Eresults.Common.WCF.BusinessEntities.Generated.MonitoringManagementBER_GEN.DeleteAlertSubscription(String companyDB, AlertSubscription obj, DbTransaction[] transaction) in d:\eResults\16R101\Glintths.Er.WebServices\Data\Glintths.Er.Common.Data\BusinessEntities\Documents\Monitoring\Generated\MonitoringManagementBER_GEN.cs:line 1195</StackTrace>
  <additionalInfo>
    <info name="MachineName" value="RPEREIRA" />
    <info name="TimeStamp" value="22/03/2016 14:20:39" />
    <info name="FullName" value="Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=4.1.0.0, Culture=neutral, PublicKeyToken=null" />
    <info name="AppDomainName" value="/LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-24-131031300376866978" />
    <info name="ThreadIdentity" value="" />
    <info name="WindowsIdentity" value="NT AUTHORITY\SYSTEM" />
  </additionalInfo>
</Exception>
Category: General
Priority: 0
EventId: 100
Severity: Error
Title:Enterprise Library Exception Handling
Machine: RPEREIRA
Application Domain: /LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-24-131031300376866978
Process Id: 748
Process Name: C:\WINDOWS\SysWOW64\inetsrv\w3wp.exe
Win32 Thread Id: 20132
Thread Name: 
Extended Properties: 
----------------------------------------
----------------------------------------
Timestamp: 22/03/2016 14:26:18
Message: <Exception handlingInstanceId="f1817804-b9fc-4613-830c-40eaa8b1a826">
  <Description>An exception of type 'System.Data.DBConcurrencyException' occurred and was caught.</Description>
  <DateTime>2016-03-22 14:26:18Z</DateTime>
  <ExceptionType>System.Data.DBConcurrencyException, System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</ExceptionType>
  <Message>DB concurrency violation.</Message>
  <Source>Glintths.Er.Common.Data</Source>
  <HelpLink />
  <Property name="Row">&lt;undefined value&gt;</Property>
  <Property name="RowCount">0</Property>
  <Property name="Data">System.Collections.ListDictionaryInternal</Property>
  <Property name="TargetSite">Void DeleteAlertSubscriptionDB(System.String, System.Data.Common.DbTransaction, Cpchs.Eresults.Common.WCF.BusinessEntities.AlertSubscription)</Property>
  <Property name="HResult">-2146232011</Property>
  <StackTrace>   at Cpchs.Eresults.Common.WCF.BusinessEntities.Generated.MonitoringManagementBER_GEN.DeleteAlertSubscriptionDB(String companyDB, DbTransaction transaction, AlertSubscription obj) in d:\eResults\16R101\Glintths.Er.WebServices\Data\Glintths.Er.Common.Data\BusinessEntities\Documents\Monitoring\Generated\MonitoringManagementBER_GEN.cs:line 1253</StackTrace>
  <additionalInfo>
    <info name="MachineName" value="RPEREIRA" />
    <info name="TimeStamp" value="22/03/2016 14:26:18" />
    <info name="FullName" value="Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=4.1.0.0, Culture=neutral, PublicKeyToken=null" />
    <info name="AppDomainName" value="/LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-24-131031300376866978" />
    <info name="ThreadIdentity" value="" />
    <info name="WindowsIdentity" value="NT AUTHORITY\SYSTEM" />
  </additionalInfo>
</Exception>
Category: General
Priority: 0
EventId: 100
Severity: Error
Title:Enterprise Library Exception Handling
Machine: RPEREIRA
Application Domain: /LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-24-131031300376866978
Process Id: 748
Process Name: C:\WINDOWS\SysWOW64\inetsrv\w3wp.exe
Win32 Thread Id: 20132
Thread Name: 
Extended Properties: 
----------------------------------------
----------------------------------------
Timestamp: 22/03/2016 14:26:19
Message: <Exception handlingInstanceId="3f189bbe-5722-4b39-b383-2f86c0af40d8">
  <Description>An exception of type 'System.Data.DBConcurrencyException' occurred and was caught.</Description>
  <DateTime>2016-03-22 14:26:18Z</DateTime>
  <ExceptionType>System.Data.DBConcurrencyException, System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</ExceptionType>
  <Message>DB concurrency violation.</Message>
  <Source>Glintths.Er.Common.Data</Source>
  <HelpLink />
  <Property name="Row">&lt;undefined value&gt;</Property>
  <Property name="RowCount">0</Property>
  <Property name="Data">System.Collections.ListDictionaryInternal</Property>
  <Property name="TargetSite">Void DeleteAlertSubscriptionDB(System.String, System.Data.Common.DbTransaction, Cpchs.Eresults.Common.WCF.BusinessEntities.AlertSubscription)</Property>
  <Property name="HResult">-2146232011</Property>
  <StackTrace>   at Cpchs.Eresults.Common.WCF.BusinessEntities.Generated.MonitoringManagementBER_GEN.DeleteAlertSubscriptionDB(String companyDB, DbTransaction transaction, AlertSubscription obj) in d:\eResults\16R101\Glintths.Er.WebServices\Data\Glintths.Er.Common.Data\BusinessEntities\Documents\Monitoring\Generated\MonitoringManagementBER_GEN.cs:line 1263
   at Cpchs.Eresults.Common.WCF.BusinessEntities.Generated.MonitoringManagementBER_GEN.DeleteAlertSubscription(String companyDB, AlertSubscription obj, DbTransaction[] transaction) in d:\eResults\16R101\Glintths.Er.WebServices\Data\Glintths.Er.Common.Data\BusinessEntities\Documents\Monitoring\Generated\MonitoringManagementBER_GEN.cs:line 1195</StackTrace>
  <additionalInfo>
    <info name="MachineName" value="RPEREIRA" />
    <info name="TimeStamp" value="22/03/2016 14:26:18" />
    <info name="FullName" value="Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=4.1.0.0, Culture=neutral, PublicKeyToken=null" />
    <info name="AppDomainName" value="/LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-24-131031300376866978" />
    <info name="ThreadIdentity" value="" />
    <info name="WindowsIdentity" value="NT AUTHORITY\SYSTEM" />
  </additionalInfo>
</Exception>
Category: General
Priority: 0
EventId: 100
Severity: Error
Title:Enterprise Library Exception Handling
Machine: RPEREIRA
Application Domain: /LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-24-131031300376866978
Process Id: 748
Process Name: C:\WINDOWS\SysWOW64\inetsrv\w3wp.exe
Win32 Thread Id: 20132
Thread Name: 
Extended Properties: 
----------------------------------------
----------------------------------------
Timestamp: 22/03/2016 14:26:34
Message: <Exception handlingInstanceId="c02afef0-ef06-414f-8762-de96f258f360">
  <Description>An exception of type 'System.Data.DBConcurrencyException' occurred and was caught.</Description>
  <DateTime>2016-03-22 14:26:34Z</DateTime>
  <ExceptionType>System.Data.DBConcurrencyException, System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</ExceptionType>
  <Message>DB concurrency violation.</Message>
  <Source>Glintths.Er.Common.Data</Source>
  <HelpLink />
  <Property name="Row">&lt;undefined value&gt;</Property>
  <Property name="RowCount">0</Property>
  <Property name="Data">System.Collections.ListDictionaryInternal</Property>
  <Property name="TargetSite">Void DeleteAlertSubscriptionDB(System.String, System.Data.Common.DbTransaction, Cpchs.Eresults.Common.WCF.BusinessEntities.AlertSubscription)</Property>
  <Property name="HResult">-2146232011</Property>
  <StackTrace>   at Cpchs.Eresults.Common.WCF.BusinessEntities.Generated.MonitoringManagementBER_GEN.DeleteAlertSubscriptionDB(String companyDB, DbTransaction transaction, AlertSubscription obj) in d:\eResults\16R101\Glintths.Er.WebServices\Data\Glintths.Er.Common.Data\BusinessEntities\Documents\Monitoring\Generated\MonitoringManagementBER_GEN.cs:line 1253</StackTrace>
  <additionalInfo>
    <info name="MachineName" value="RPEREIRA" />
    <info name="TimeStamp" value="22/03/2016 14:26:34" />
    <info name="FullName" value="Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=4.1.0.0, Culture=neutral, PublicKeyToken=null" />
    <info name="AppDomainName" value="/LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-24-131031300376866978" />
    <info name="ThreadIdentity" value="" />
    <info name="WindowsIdentity" value="NT AUTHORITY\SYSTEM" />
  </additionalInfo>
</Exception>
Category: General
Priority: 0
EventId: 100
Severity: Error
Title:Enterprise Library Exception Handling
Machine: RPEREIRA
Application Domain: /LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-24-131031300376866978
Process Id: 748
Process Name: C:\WINDOWS\SysWOW64\inetsrv\w3wp.exe
Win32 Thread Id: 20132
Thread Name: 
Extended Properties: 
----------------------------------------
----------------------------------------
Timestamp: 22/03/2016 14:26:34
Message: <Exception handlingInstanceId="54864fab-87c9-400f-83e5-70f0c0dda20c">
  <Description>An exception of type 'System.Data.DBConcurrencyException' occurred and was caught.</Description>
  <DateTime>2016-03-22 14:26:34Z</DateTime>
  <ExceptionType>System.Data.DBConcurrencyException, System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</ExceptionType>
  <Message>DB concurrency violation.</Message>
  <Source>Glintths.Er.Common.Data</Source>
  <HelpLink />
  <Property name="Row">&lt;undefined value&gt;</Property>
  <Property name="RowCount">0</Property>
  <Property name="Data">System.Collections.ListDictionaryInternal</Property>
  <Property name="TargetSite">Void DeleteAlertSubscriptionDB(System.String, System.Data.Common.DbTransaction, Cpchs.Eresults.Common.WCF.BusinessEntities.AlertSubscription)</Property>
  <Property name="HResult">-2146232011</Property>
  <StackTrace>   at Cpchs.Eresults.Common.WCF.BusinessEntities.Generated.MonitoringManagementBER_GEN.DeleteAlertSubscriptionDB(String companyDB, DbTransaction transaction, AlertSubscription obj) in d:\eResults\16R101\Glintths.Er.WebServices\Data\Glintths.Er.Common.Data\BusinessEntities\Documents\Monitoring\Generated\MonitoringManagementBER_GEN.cs:line 1263
   at Cpchs.Eresults.Common.WCF.BusinessEntities.Generated.MonitoringManagementBER_GEN.DeleteAlertSubscription(String companyDB, AlertSubscription obj, DbTransaction[] transaction) in d:\eResults\16R101\Glintths.Er.WebServices\Data\Glintths.Er.Common.Data\BusinessEntities\Documents\Monitoring\Generated\MonitoringManagementBER_GEN.cs:line 1195</StackTrace>
  <additionalInfo>
    <info name="MachineName" value="RPEREIRA" />
    <info name="TimeStamp" value="22/03/2016 14:26:34" />
    <info name="FullName" value="Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=4.1.0.0, Culture=neutral, PublicKeyToken=null" />
    <info name="AppDomainName" value="/LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-24-131031300376866978" />
    <info name="ThreadIdentity" value="" />
    <info name="WindowsIdentity" value="NT AUTHORITY\SYSTEM" />
  </additionalInfo>
</Exception>
Category: General
Priority: 0
EventId: 100
Severity: Error
Title:Enterprise Library Exception Handling
Machine: RPEREIRA
Application Domain: /LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-24-131031300376866978
Process Id: 748
Process Name: C:\WINDOWS\SysWOW64\inetsrv\w3wp.exe
Win32 Thread Id: 20132
Thread Name: 
Extended Properties: 
----------------------------------------
----------------------------------------
Timestamp: 22/03/2016 14:27:54
Message: <Exception handlingInstanceId="bd5f0028-2602-453d-bc53-cc7cc85e59bc">
  <Description>An exception of type 'System.Data.DBConcurrencyException' occurred and was caught.</Description>
  <DateTime>2016-03-22 14:27:54Z</DateTime>
  <ExceptionType>System.Data.DBConcurrencyException, System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</ExceptionType>
  <Message>DB concurrency violation.</Message>
  <Source>Glintths.Er.Common.Data</Source>
  <HelpLink />
  <Property name="Row">&lt;undefined value&gt;</Property>
  <Property name="RowCount">0</Property>
  <Property name="Data">System.Collections.ListDictionaryInternal</Property>
  <Property name="TargetSite">Void DeleteAlertSubscriptionDB(System.String, System.Data.Common.DbTransaction, Cpchs.Eresults.Common.WCF.BusinessEntities.AlertSubscription)</Property>
  <Property name="HResult">-2146232011</Property>
  <StackTrace>   at Cpchs.Eresults.Common.WCF.BusinessEntities.Generated.MonitoringManagementBER_GEN.DeleteAlertSubscriptionDB(String companyDB, DbTransaction transaction, AlertSubscription obj) in d:\eResults\16R101\Glintths.Er.WebServices\Data\Glintths.Er.Common.Data\BusinessEntities\Documents\Monitoring\Generated\MonitoringManagementBER_GEN.cs:line 1253</StackTrace>
  <additionalInfo>
    <info name="MachineName" value="RPEREIRA" />
    <info name="TimeStamp" value="22/03/2016 14:27:54" />
    <info name="FullName" value="Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=4.1.0.0, Culture=neutral, PublicKeyToken=null" />
    <info name="AppDomainName" value="/LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-24-131031300376866978" />
    <info name="ThreadIdentity" value="" />
    <info name="WindowsIdentity" value="NT AUTHORITY\SYSTEM" />
  </additionalInfo>
</Exception>
Category: General
Priority: 0
EventId: 100
Severity: Error
Title:Enterprise Library Exception Handling
Machine: RPEREIRA
Application Domain: /LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-24-131031300376866978
Process Id: 748
Process Name: C:\WINDOWS\SysWOW64\inetsrv\w3wp.exe
Win32 Thread Id: 20132
Thread Name: 
Extended Properties: 
----------------------------------------
----------------------------------------
Timestamp: 22/03/2016 14:27:54
Message: <Exception handlingInstanceId="cb788c11-f3f0-487d-b01d-945998ba6b10">
  <Description>An exception of type 'System.Data.DBConcurrencyException' occurred and was caught.</Description>
  <DateTime>2016-03-22 14:27:54Z</DateTime>
  <ExceptionType>System.Data.DBConcurrencyException, System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</ExceptionType>
  <Message>DB concurrency violation.</Message>
  <Source>Glintths.Er.Common.Data</Source>
  <HelpLink />
  <Property name="Row">&lt;undefined value&gt;</Property>
  <Property name="RowCount">0</Property>
  <Property name="Data">System.Collections.ListDictionaryInternal</Property>
  <Property name="TargetSite">Void DeleteAlertSubscriptionDB(System.String, System.Data.Common.DbTransaction, Cpchs.Eresults.Common.WCF.BusinessEntities.AlertSubscription)</Property>
  <Property name="HResult">-2146232011</Property>
  <StackTrace>   at Cpchs.Eresults.Common.WCF.BusinessEntities.Generated.MonitoringManagementBER_GEN.DeleteAlertSubscriptionDB(String companyDB, DbTransaction transaction, AlertSubscription obj) in d:\eResults\16R101\Glintths.Er.WebServices\Data\Glintths.Er.Common.Data\BusinessEntities\Documents\Monitoring\Generated\MonitoringManagementBER_GEN.cs:line 1263
   at Cpchs.Eresults.Common.WCF.BusinessEntities.Generated.MonitoringManagementBER_GEN.DeleteAlertSubscription(String companyDB, AlertSubscription obj, DbTransaction[] transaction) in d:\eResults\16R101\Glintths.Er.WebServices\Data\Glintths.Er.Common.Data\BusinessEntities\Documents\Monitoring\Generated\MonitoringManagementBER_GEN.cs:line 1195</StackTrace>
  <additionalInfo>
    <info name="MachineName" value="RPEREIRA" />
    <info name="TimeStamp" value="22/03/2016 14:27:54" />
    <info name="FullName" value="Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=4.1.0.0, Culture=neutral, PublicKeyToken=null" />
    <info name="AppDomainName" value="/LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-24-131031300376866978" />
    <info name="ThreadIdentity" value="" />
    <info name="WindowsIdentity" value="NT AUTHORITY\SYSTEM" />
  </additionalInfo>
</Exception>
Category: General
Priority: 0
EventId: 100
Severity: Error
Title:Enterprise Library Exception Handling
Machine: RPEREIRA
Application Domain: /LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-24-131031300376866978
Process Id: 748
Process Name: C:\WINDOWS\SysWOW64\inetsrv\w3wp.exe
Win32 Thread Id: 20132
Thread Name: 
Extended Properties: 
----------------------------------------
----------------------------------------
Timestamp: 23/03/2016 10:58:02
Message: <Exception handlingInstanceId="b7283d96-ed70-47bc-98ea-acbd6b4795af">
  <Description>An exception of type 'Oracle.DataAccess.Client.OracleException' occurred and was caught.</Description>
  <DateTime>2016-03-23 10:58:02Z</DateTime>
  <ExceptionType>Oracle.DataAccess.Client.OracleException, Oracle.DataAccess, Version=2.112.3.0, Culture=neutral, PublicKeyToken=89b483f429c47342</ExceptionType>
  <Message>ORA-20005: CONTEXTO DE ACESSO INVALIDO
ORA-06512: at "ERESULTS_V2_16R101.PCK_ER_DOCS", line 311
ORA-06512: at "ERESULTS_V2_16R101.PCK_ER_DOCS", line 2431
ORA-06512: at line 1</Message>
  <Source>Oracle Data Provider for .NET</Source>
  <HelpLink />
  <Property name="Errors">Oracle.DataAccess.Client.OracleErrorCollection</Property>
  <Property name="DataSource">HSDEV</Property>
  <Property name="Procedure">PCK_ER_DOCS.GetDocumentsByMultiCriteria</Property>
  <Property name="Number">20005</Property>
  <Property name="ErrorCode">-2147467259</Property>
  <Property name="Data">System.Collections.ListDictionaryInternal</Property>
  <Property name="TargetSite">Void HandleErrorHelper(Int32, Oracle.DataAccess.Client.OracleConnection, IntPtr, Oracle.DataAccess.Client.OpoSqlValCtx*, System.Object, System.String, Boolean)</Property>
  <Property name="HResult">-2147467259</Property>
  <StackTrace>   at Oracle.DataAccess.Client.OracleException.HandleErrorHelper(Int32 errCode, OracleConnection conn, IntPtr opsErrCtx, OpoSqlValCtx* pOpoSqlValCtx, Object src, String procedure, Boolean bCheck)
   at Oracle.DataAccess.Client.OracleException.HandleError(Int32 errCode, OracleConnection conn, String procedure, IntPtr opsErrCtx, OpoSqlValCtx* pOpoSqlValCtx, Object src, Boolean bCheck)
   at Oracle.DataAccess.Client.OracleCommand.ExecuteReader(Boolean requery, Boolean fillRequest, CommandBehavior behavior)
   at Oracle.DataAccess.Client.OracleCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.DoExecuteReader(DbCommand command, CommandBehavior cmdBehavior)
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.ExecuteReader(DbCommand command)
   at EntLibContrib.Data.OdpNet.OracleDatabase.ExecuteReader(DbCommand command)
   at Cpchs.Eresults.Common.WCF.BusinessEntities.DocumentManagementBER.GetDocsDB(String companyDB, String documentRef, String documentExternalId, String entitiesIds, String episodeType, String episodeId, String patientId, String patientType, Nullable`1 episodeStartDate, Nullable`1 episodeEndDate, String institution, String place, String application, String documentType, Nullable`1 executionStartDate, Nullable`1 executionEndDate, Nullable`1 validationStartDate, Nullable`1 validationEndDate, Nullable`1 emissionStartDate, Nullable`1 emissionEndDate, String reqService, String execService, String globalFilters, String docsSession, String servsSession, String username, Nullable`1 pageNumber, Nullable`1 itemsPerPage, String orderField, String orderType, String report, String isPublic, Nullable`1 workspaceId, String filterString, String period, Nullable`1&amp; resultCount) in d:\eResults\16R101\Glintths.Er.WebServices\Data\Glintths.Er.Common.Data\BusinessEntities\Documents\Document\DocumentManagementBER.cs:line 602</StackTrace>
  <additionalInfo>
    <info name="MachineName" value="RPEREIRA" />
    <info name="TimeStamp" value="23/03/2016 10:58:02" />
    <info name="FullName" value="Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=4.1.0.0, Culture=neutral, PublicKeyToken=null" />
    <info name="AppDomainName" value="/LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-7-131032042808169828" />
    <info name="ThreadIdentity" value="" />
    <info name="WindowsIdentity" value="NT AUTHORITY\SYSTEM" />
  </additionalInfo>
</Exception>
Category: General
Priority: 0
EventId: 100
Severity: Error
Title:Enterprise Library Exception Handling
Machine: RPEREIRA
Application Domain: /LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-7-131032042808169828
Process Id: 20840
Process Name: C:\WINDOWS\SysWOW64\inetsrv\w3wp.exe
Win32 Thread Id: 14724
Thread Name: 
Extended Properties: 
----------------------------------------
----------------------------------------
Timestamp: 13/04/2016 08:56:34
Message: <Exception handlingInstanceId="6aa49c69-c25e-4c49-becc-8b612d0f4afc">
  <Description>An exception of type 'Oracle.DataAccess.Client.OracleException' occurred and was caught.</Description>
  <DateTime>2016-04-13 09:56:34Z</DateTime>
  <ExceptionType>Oracle.DataAccess.Client.OracleException, Oracle.DataAccess, Version=2.112.3.0, Culture=neutral, PublicKeyToken=89b483f429c47342</ExceptionType>
  <Message>ORA-20005: CONTEXTO DE ACESSO INVALIDO
ORA-06512: at "ERESULTS_V2_16R101.PCK_ER_DOCS", line 311
ORA-06512: at "ERESULTS_V2_16R101.PCK_ER_DOCS", line 2431
ORA-06512: at line 1</Message>
  <Source>Oracle Data Provider for .NET</Source>
  <HelpLink />
  <Property name="Errors">Oracle.DataAccess.Client.OracleErrorCollection</Property>
  <Property name="DataSource">HSDEV</Property>
  <Property name="Procedure">PCK_ER_DOCS.GetDocumentsByMultiCriteria</Property>
  <Property name="Number">20005</Property>
  <Property name="ErrorCode">-2147467259</Property>
  <Property name="Data">System.Collections.ListDictionaryInternal</Property>
  <Property name="TargetSite">Void HandleErrorHelper(Int32, Oracle.DataAccess.Client.OracleConnection, IntPtr, Oracle.DataAccess.Client.OpoSqlValCtx*, System.Object, System.String, Boolean)</Property>
  <Property name="HResult">-2147467259</Property>
  <StackTrace>   at Oracle.DataAccess.Client.OracleException.HandleErrorHelper(Int32 errCode, OracleConnection conn, IntPtr opsErrCtx, OpoSqlValCtx* pOpoSqlValCtx, Object src, String procedure, Boolean bCheck)
   at Oracle.DataAccess.Client.OracleException.HandleError(Int32 errCode, OracleConnection conn, String procedure, IntPtr opsErrCtx, OpoSqlValCtx* pOpoSqlValCtx, Object src, Boolean bCheck)
   at Oracle.DataAccess.Client.OracleCommand.ExecuteReader(Boolean requery, Boolean fillRequest, CommandBehavior behavior)
   at Oracle.DataAccess.Client.OracleCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.DoExecuteReader(DbCommand command, CommandBehavior cmdBehavior)
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.ExecuteReader(DbCommand command)
   at EntLibContrib.Data.OdpNet.OracleDatabase.ExecuteReader(DbCommand command)
   at Cpchs.Eresults.Common.WCF.BusinessEntities.DocumentManagementBER.GetDocsDB(String companyDB, String documentRef, String documentExternalId, String entitiesIds, String episodeType, String episodeId, String patientId, String patientType, Nullable`1 episodeStartDate, Nullable`1 episodeEndDate, String institution, String place, String application, String documentType, Nullable`1 executionStartDate, Nullable`1 executionEndDate, Nullable`1 validationStartDate, Nullable`1 validationEndDate, Nullable`1 emissionStartDate, Nullable`1 emissionEndDate, String reqService, String execService, String globalFilters, String docsSession, String servsSession, String username, Nullable`1 pageNumber, Nullable`1 itemsPerPage, String orderField, String orderType, String report, String isPublic, Nullable`1 workspaceId, String filterString, String period, Nullable`1&amp; resultCount) in d:\eResults\16R101\Glintths.Er.WebServices\Data\Glintths.Er.Common.Data\BusinessEntities\Documents\Document\DocumentManagementBER.cs:line 602</StackTrace>
  <additionalInfo>
    <info name="MachineName" value="RPEREIRA" />
    <info name="TimeStamp" value="13/04/2016 08:56:34" />
    <info name="FullName" value="Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=4.1.0.0, Culture=neutral, PublicKeyToken=null" />
    <info name="AppDomainName" value="/LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-7-131050113937592137" />
    <info name="ThreadIdentity" value="" />
    <info name="WindowsIdentity" value="NT AUTHORITY\SYSTEM" />
  </additionalInfo>
</Exception>
Category: General
Priority: 0
EventId: 100
Severity: Error
Title:Enterprise Library Exception Handling
Machine: RPEREIRA
Application Domain: /LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-7-131050113937592137
Process Id: 13368
Process Name: C:\WINDOWS\SysWOW64\inetsrv\w3wp.exe
Win32 Thread Id: 5920
Thread Name: 
Extended Properties: 
----------------------------------------
----------------------------------------
Timestamp: 13/04/2016 09:08:59
Message: <Exception handlingInstanceId="1d242be2-24cc-42ec-aa3f-37a9cd710d18">
  <Description>An exception of type 'Oracle.DataAccess.Client.OracleException' occurred and was caught.</Description>
  <DateTime>2016-04-13 10:08:59Z</DateTime>
  <ExceptionType>Oracle.DataAccess.Client.OracleException, Oracle.DataAccess, Version=2.112.3.0, Culture=neutral, PublicKeyToken=89b483f429c47342</ExceptionType>
  <Message>ORA-20005: CONTEXTO DE ACESSO INVALIDO
ORA-06512: at "ERESULTS_V2_16R101.PCK_ER_DOCS", line 311
ORA-06512: at "ERESULTS_V2_16R101.PCK_ER_DOCS", line 2431
ORA-06512: at line 1</Message>
  <Source>Oracle Data Provider for .NET</Source>
  <HelpLink />
  <Property name="Errors">Oracle.DataAccess.Client.OracleErrorCollection</Property>
  <Property name="DataSource">HSDEV</Property>
  <Property name="Procedure">PCK_ER_DOCS.GetDocumentsByMultiCriteria</Property>
  <Property name="Number">20005</Property>
  <Property name="ErrorCode">-2147467259</Property>
  <Property name="Data">System.Collections.ListDictionaryInternal</Property>
  <Property name="TargetSite">Void HandleErrorHelper(Int32, Oracle.DataAccess.Client.OracleConnection, IntPtr, Oracle.DataAccess.Client.OpoSqlValCtx*, System.Object, System.String, Boolean)</Property>
  <Property name="HResult">-2147467259</Property>
  <StackTrace>   at Oracle.DataAccess.Client.OracleException.HandleErrorHelper(Int32 errCode, OracleConnection conn, IntPtr opsErrCtx, OpoSqlValCtx* pOpoSqlValCtx, Object src, String procedure, Boolean bCheck)
   at Oracle.DataAccess.Client.OracleException.HandleError(Int32 errCode, OracleConnection conn, String procedure, IntPtr opsErrCtx, OpoSqlValCtx* pOpoSqlValCtx, Object src, Boolean bCheck)
   at Oracle.DataAccess.Client.OracleCommand.ExecuteReader(Boolean requery, Boolean fillRequest, CommandBehavior behavior)
   at Oracle.DataAccess.Client.OracleCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.DoExecuteReader(DbCommand command, CommandBehavior cmdBehavior)
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.ExecuteReader(DbCommand command)
   at EntLibContrib.Data.OdpNet.OracleDatabase.ExecuteReader(DbCommand command)
   at Cpchs.Eresults.Common.WCF.BusinessEntities.DocumentManagementBER.GetDocsDB(String companyDB, String documentRef, String documentExternalId, String entitiesIds, String episodeType, String episodeId, String patientId, String patientType, Nullable`1 episodeStartDate, Nullable`1 episodeEndDate, String institution, String place, String application, String documentType, Nullable`1 executionStartDate, Nullable`1 executionEndDate, Nullable`1 validationStartDate, Nullable`1 validationEndDate, Nullable`1 emissionStartDate, Nullable`1 emissionEndDate, String reqService, String execService, String globalFilters, String docsSession, String servsSession, String username, Nullable`1 pageNumber, Nullable`1 itemsPerPage, String orderField, String orderType, String report, String isPublic, Nullable`1 workspaceId, String filterString, String period, Nullable`1&amp; resultCount) in d:\eResults\16R101\Glintths.Er.WebServices\Data\Glintths.Er.Common.Data\BusinessEntities\Documents\Document\DocumentManagementBER.cs:line 602</StackTrace>
  <additionalInfo>
    <info name="MachineName" value="RPEREIRA" />
    <info name="TimeStamp" value="13/04/2016 09:08:59" />
    <info name="FullName" value="Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=4.1.0.0, Culture=neutral, PublicKeyToken=null" />
    <info name="AppDomainName" value="/LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-7-131050113937592137" />
    <info name="ThreadIdentity" value="" />
    <info name="WindowsIdentity" value="NT AUTHORITY\SYSTEM" />
  </additionalInfo>
</Exception>
Category: General
Priority: 0
EventId: 100
Severity: Error
Title:Enterprise Library Exception Handling
Machine: RPEREIRA
Application Domain: /LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-7-131050113937592137
Process Id: 13368
Process Name: C:\WINDOWS\SysWOW64\inetsrv\w3wp.exe
Win32 Thread Id: 10384
Thread Name: 
Extended Properties: 
----------------------------------------
----------------------------------------
Timestamp: 13/04/2016 09:09:33
Message: <Exception handlingInstanceId="85a595f5-a07b-4187-8d97-6abaeb109e63">
  <Description>An exception of type 'Oracle.DataAccess.Client.OracleException' occurred and was caught.</Description>
  <DateTime>2016-04-13 10:09:33Z</DateTime>
  <ExceptionType>Oracle.DataAccess.Client.OracleException, Oracle.DataAccess, Version=2.112.3.0, Culture=neutral, PublicKeyToken=89b483f429c47342</ExceptionType>
  <Message>ORA-20005: CONTEXTO DE ACESSO INVALIDO
ORA-06512: at "ERESULTS_V2_16R101.PCK_ER_DOCS", line 311
ORA-06512: at "ERESULTS_V2_16R101.PCK_ER_DOCS", line 2431
ORA-06512: at line 1</Message>
  <Source>Oracle Data Provider for .NET</Source>
  <HelpLink />
  <Property name="Errors">Oracle.DataAccess.Client.OracleErrorCollection</Property>
  <Property name="DataSource">HSDEV</Property>
  <Property name="Procedure">PCK_ER_DOCS.GetDocumentsByMultiCriteria</Property>
  <Property name="Number">20005</Property>
  <Property name="ErrorCode">-2147467259</Property>
  <Property name="Data">System.Collections.ListDictionaryInternal</Property>
  <Property name="TargetSite">Void HandleErrorHelper(Int32, Oracle.DataAccess.Client.OracleConnection, IntPtr, Oracle.DataAccess.Client.OpoSqlValCtx*, System.Object, System.String, Boolean)</Property>
  <Property name="HResult">-2147467259</Property>
  <StackTrace>   at Oracle.DataAccess.Client.OracleException.HandleErrorHelper(Int32 errCode, OracleConnection conn, IntPtr opsErrCtx, OpoSqlValCtx* pOpoSqlValCtx, Object src, String procedure, Boolean bCheck)
   at Oracle.DataAccess.Client.OracleException.HandleError(Int32 errCode, OracleConnection conn, String procedure, IntPtr opsErrCtx, OpoSqlValCtx* pOpoSqlValCtx, Object src, Boolean bCheck)
   at Oracle.DataAccess.Client.OracleCommand.ExecuteReader(Boolean requery, Boolean fillRequest, CommandBehavior behavior)
   at Oracle.DataAccess.Client.OracleCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.DoExecuteReader(DbCommand command, CommandBehavior cmdBehavior)
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.ExecuteReader(DbCommand command)
   at EntLibContrib.Data.OdpNet.OracleDatabase.ExecuteReader(DbCommand command)
   at Cpchs.Eresults.Common.WCF.BusinessEntities.DocumentManagementBER.GetDocsDB(String companyDB, String documentRef, String documentExternalId, String entitiesIds, String episodeType, String episodeId, String patientId, String patientType, Nullable`1 episodeStartDate, Nullable`1 episodeEndDate, String institution, String place, String application, String documentType, Nullable`1 executionStartDate, Nullable`1 executionEndDate, Nullable`1 validationStartDate, Nullable`1 validationEndDate, Nullable`1 emissionStartDate, Nullable`1 emissionEndDate, String reqService, String execService, String globalFilters, String docsSession, String servsSession, String username, Nullable`1 pageNumber, Nullable`1 itemsPerPage, String orderField, String orderType, String report, String isPublic, Nullable`1 workspaceId, String filterString, String period, Nullable`1&amp; resultCount) in d:\eResults\16R101\Glintths.Er.WebServices\Data\Glintths.Er.Common.Data\BusinessEntities\Documents\Document\DocumentManagementBER.cs:line 602</StackTrace>
  <additionalInfo>
    <info name="MachineName" value="RPEREIRA" />
    <info name="TimeStamp" value="13/04/2016 09:09:33" />
    <info name="FullName" value="Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=4.1.0.0, Culture=neutral, PublicKeyToken=null" />
    <info name="AppDomainName" value="/LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-7-131050113937592137" />
    <info name="ThreadIdentity" value="" />
    <info name="WindowsIdentity" value="NT AUTHORITY\SYSTEM" />
  </additionalInfo>
</Exception>
Category: General
Priority: 0
EventId: 100
Severity: Error
Title:Enterprise Library Exception Handling
Machine: RPEREIRA
Application Domain: /LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-7-131050113937592137
Process Id: 13368
Process Name: C:\WINDOWS\SysWOW64\inetsrv\w3wp.exe
Win32 Thread Id: 5076
Thread Name: 
Extended Properties: 
----------------------------------------
----------------------------------------
Timestamp: 13/04/2016 09:11:42
Message: <Exception handlingInstanceId="6cdf2c23-2ff7-4c64-871e-b3d222008c54">
  <Description>An exception of type 'Oracle.DataAccess.Client.OracleException' occurred and was caught.</Description>
  <DateTime>2016-04-13 10:11:42Z</DateTime>
  <ExceptionType>Oracle.DataAccess.Client.OracleException, Oracle.DataAccess, Version=2.112.3.0, Culture=neutral, PublicKeyToken=89b483f429c47342</ExceptionType>
  <Message>ORA-20005: CONTEXTO DE ACESSO INVALIDO
ORA-06512: at "ERESULTS_V2_16R101.PCK_ER_DOCS", line 311
ORA-06512: at "ERESULTS_V2_16R101.PCK_ER_DOCS", line 2431
ORA-06512: at line 1</Message>
  <Source>Oracle Data Provider for .NET</Source>
  <HelpLink />
  <Property name="Errors">Oracle.DataAccess.Client.OracleErrorCollection</Property>
  <Property name="DataSource">HSDEV</Property>
  <Property name="Procedure">PCK_ER_DOCS.GetDocumentsByMultiCriteria</Property>
  <Property name="Number">20005</Property>
  <Property name="ErrorCode">-2147467259</Property>
  <Property name="Data">System.Collections.ListDictionaryInternal</Property>
  <Property name="TargetSite">Void HandleErrorHelper(Int32, Oracle.DataAccess.Client.OracleConnection, IntPtr, Oracle.DataAccess.Client.OpoSqlValCtx*, System.Object, System.String, Boolean)</Property>
  <Property name="HResult">-2147467259</Property>
  <StackTrace>   at Oracle.DataAccess.Client.OracleException.HandleErrorHelper(Int32 errCode, OracleConnection conn, IntPtr opsErrCtx, OpoSqlValCtx* pOpoSqlValCtx, Object src, String procedure, Boolean bCheck)
   at Oracle.DataAccess.Client.OracleException.HandleError(Int32 errCode, OracleConnection conn, String procedure, IntPtr opsErrCtx, OpoSqlValCtx* pOpoSqlValCtx, Object src, Boolean bCheck)
   at Oracle.DataAccess.Client.OracleCommand.ExecuteReader(Boolean requery, Boolean fillRequest, CommandBehavior behavior)
   at Oracle.DataAccess.Client.OracleCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.DoExecuteReader(DbCommand command, CommandBehavior cmdBehavior)
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.ExecuteReader(DbCommand command)
   at EntLibContrib.Data.OdpNet.OracleDatabase.ExecuteReader(DbCommand command)
   at Cpchs.Eresults.Common.WCF.BusinessEntities.DocumentManagementBER.GetDocsDB(String companyDB, String documentRef, String documentExternalId, String entitiesIds, String episodeType, String episodeId, String patientId, String patientType, Nullable`1 episodeStartDate, Nullable`1 episodeEndDate, String institution, String place, String application, String documentType, Nullable`1 executionStartDate, Nullable`1 executionEndDate, Nullable`1 validationStartDate, Nullable`1 validationEndDate, Nullable`1 emissionStartDate, Nullable`1 emissionEndDate, String reqService, String execService, String globalFilters, String docsSession, String servsSession, String username, Nullable`1 pageNumber, Nullable`1 itemsPerPage, String orderField, String orderType, String report, String isPublic, Nullable`1 workspaceId, String filterString, String period, Nullable`1&amp; resultCount) in d:\eResults\16R101\Glintths.Er.WebServices\Data\Glintths.Er.Common.Data\BusinessEntities\Documents\Document\DocumentManagementBER.cs:line 602</StackTrace>
  <additionalInfo>
    <info name="MachineName" value="RPEREIRA" />
    <info name="TimeStamp" value="13/04/2016 09:11:42" />
    <info name="FullName" value="Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=4.1.0.0, Culture=neutral, PublicKeyToken=null" />
    <info name="AppDomainName" value="/LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-7-131050113937592137" />
    <info name="ThreadIdentity" value="" />
    <info name="WindowsIdentity" value="NT AUTHORITY\SYSTEM" />
  </additionalInfo>
</Exception>
Category: General
Priority: 0
EventId: 100
Severity: Error
Title:Enterprise Library Exception Handling
Machine: RPEREIRA
Application Domain: /LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-7-131050113937592137
Process Id: 13368
Process Name: C:\WINDOWS\SysWOW64\inetsrv\w3wp.exe
Win32 Thread Id: 19600
Thread Name: 
Extended Properties: 
----------------------------------------
----------------------------------------
Timestamp: 13/04/2016 09:12:36
Message: <Exception handlingInstanceId="e78a3616-ea3c-4128-82d4-814747ce9cf6">
  <Description>An exception of type 'Oracle.DataAccess.Client.OracleException' occurred and was caught.</Description>
  <DateTime>2016-04-13 10:12:36Z</DateTime>
  <ExceptionType>Oracle.DataAccess.Client.OracleException, Oracle.DataAccess, Version=2.112.3.0, Culture=neutral, PublicKeyToken=89b483f429c47342</ExceptionType>
  <Message>ORA-20005: CONTEXTO DE ACESSO INVALIDO
ORA-06512: at "ERESULTS_V2_16R101.PCK_ER_DOCS", line 311
ORA-06512: at "ERESULTS_V2_16R101.PCK_ER_DOCS", line 2431
ORA-06512: at line 1</Message>
  <Source>Oracle Data Provider for .NET</Source>
  <HelpLink />
  <Property name="Errors">Oracle.DataAccess.Client.OracleErrorCollection</Property>
  <Property name="DataSource">HSDEV</Property>
  <Property name="Procedure">PCK_ER_DOCS.GetDocumentsByMultiCriteria</Property>
  <Property name="Number">20005</Property>
  <Property name="ErrorCode">-2147467259</Property>
  <Property name="Data">System.Collections.ListDictionaryInternal</Property>
  <Property name="TargetSite">Void HandleErrorHelper(Int32, Oracle.DataAccess.Client.OracleConnection, IntPtr, Oracle.DataAccess.Client.OpoSqlValCtx*, System.Object, System.String, Boolean)</Property>
  <Property name="HResult">-2147467259</Property>
  <StackTrace>   at Oracle.DataAccess.Client.OracleException.HandleErrorHelper(Int32 errCode, OracleConnection conn, IntPtr opsErrCtx, OpoSqlValCtx* pOpoSqlValCtx, Object src, String procedure, Boolean bCheck)
   at Oracle.DataAccess.Client.OracleException.HandleError(Int32 errCode, OracleConnection conn, String procedure, IntPtr opsErrCtx, OpoSqlValCtx* pOpoSqlValCtx, Object src, Boolean bCheck)
   at Oracle.DataAccess.Client.OracleCommand.ExecuteReader(Boolean requery, Boolean fillRequest, CommandBehavior behavior)
   at Oracle.DataAccess.Client.OracleCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.DoExecuteReader(DbCommand command, CommandBehavior cmdBehavior)
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.ExecuteReader(DbCommand command)
   at EntLibContrib.Data.OdpNet.OracleDatabase.ExecuteReader(DbCommand command)
   at Cpchs.Eresults.Common.WCF.BusinessEntities.DocumentManagementBER.GetDocsDB(String companyDB, String documentRef, String documentExternalId, String entitiesIds, String episodeType, String episodeId, String patientId, String patientType, Nullable`1 episodeStartDate, Nullable`1 episodeEndDate, String institution, String place, String application, String documentType, Nullable`1 executionStartDate, Nullable`1 executionEndDate, Nullable`1 validationStartDate, Nullable`1 validationEndDate, Nullable`1 emissionStartDate, Nullable`1 emissionEndDate, String reqService, String execService, String globalFilters, String docsSession, String servsSession, String username, Nullable`1 pageNumber, Nullable`1 itemsPerPage, String orderField, String orderType, String report, String isPublic, Nullable`1 workspaceId, String filterString, String period, Nullable`1&amp; resultCount) in d:\eResults\16R101\Glintths.Er.WebServices\Data\Glintths.Er.Common.Data\BusinessEntities\Documents\Document\DocumentManagementBER.cs:line 602</StackTrace>
  <additionalInfo>
    <info name="MachineName" value="RPEREIRA" />
    <info name="TimeStamp" value="13/04/2016 09:12:36" />
    <info name="FullName" value="Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=4.1.0.0, Culture=neutral, PublicKeyToken=null" />
    <info name="AppDomainName" value="/LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-7-131050113937592137" />
    <info name="ThreadIdentity" value="" />
    <info name="WindowsIdentity" value="NT AUTHORITY\SYSTEM" />
  </additionalInfo>
</Exception>
Category: General
Priority: 0
EventId: 100
Severity: Error
Title:Enterprise Library Exception Handling
Machine: RPEREIRA
Application Domain: /LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-7-131050113937592137
Process Id: 13368
Process Name: C:\WINDOWS\SysWOW64\inetsrv\w3wp.exe
Win32 Thread Id: 5076
Thread Name: 
Extended Properties: 
----------------------------------------
----------------------------------------
Timestamp: 13/04/2016 09:18:22
Message: <Exception handlingInstanceId="e03b8141-447e-469f-88ab-85548006951c">
  <Description>An exception of type 'Oracle.DataAccess.Client.OracleException' occurred and was caught.</Description>
  <DateTime>2016-04-13 10:18:22Z</DateTime>
  <ExceptionType>Oracle.DataAccess.Client.OracleException, Oracle.DataAccess, Version=2.112.3.0, Culture=neutral, PublicKeyToken=89b483f429c47342</ExceptionType>
  <Message>ORA-20005: CONTEXTO DE ACESSO INVALIDO
ORA-06512: at "ERESULTS_V2_16R101.PCK_ER_DOCS", line 311
ORA-06512: at "ERESULTS_V2_16R101.PCK_ER_DOCS", line 2431
ORA-06512: at line 1</Message>
  <Source>Oracle Data Provider for .NET</Source>
  <HelpLink />
  <Property name="Errors">Oracle.DataAccess.Client.OracleErrorCollection</Property>
  <Property name="DataSource">HSDEV</Property>
  <Property name="Procedure">PCK_ER_DOCS.GetDocumentsByMultiCriteria</Property>
  <Property name="Number">20005</Property>
  <Property name="ErrorCode">-2147467259</Property>
  <Property name="Data">System.Collections.ListDictionaryInternal</Property>
  <Property name="TargetSite">Void HandleErrorHelper(Int32, Oracle.DataAccess.Client.OracleConnection, IntPtr, Oracle.DataAccess.Client.OpoSqlValCtx*, System.Object, System.String, Boolean)</Property>
  <Property name="HResult">-2147467259</Property>
  <StackTrace>   at Oracle.DataAccess.Client.OracleException.HandleErrorHelper(Int32 errCode, OracleConnection conn, IntPtr opsErrCtx, OpoSqlValCtx* pOpoSqlValCtx, Object src, String procedure, Boolean bCheck)
   at Oracle.DataAccess.Client.OracleException.HandleError(Int32 errCode, OracleConnection conn, String procedure, IntPtr opsErrCtx, OpoSqlValCtx* pOpoSqlValCtx, Object src, Boolean bCheck)
   at Oracle.DataAccess.Client.OracleCommand.ExecuteReader(Boolean requery, Boolean fillRequest, CommandBehavior behavior)
   at Oracle.DataAccess.Client.OracleCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.DoExecuteReader(DbCommand command, CommandBehavior cmdBehavior)
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.ExecuteReader(DbCommand command)
   at EntLibContrib.Data.OdpNet.OracleDatabase.ExecuteReader(DbCommand command)
   at Cpchs.Eresults.Common.WCF.BusinessEntities.DocumentManagementBER.GetDocsDB(String companyDB, String documentRef, String documentExternalId, String entitiesIds, String episodeType, String episodeId, String patientId, String patientType, Nullable`1 episodeStartDate, Nullable`1 episodeEndDate, String institution, String place, String application, String documentType, Nullable`1 executionStartDate, Nullable`1 executionEndDate, Nullable`1 validationStartDate, Nullable`1 validationEndDate, Nullable`1 emissionStartDate, Nullable`1 emissionEndDate, String reqService, String execService, String globalFilters, String docsSession, String servsSession, String username, Nullable`1 pageNumber, Nullable`1 itemsPerPage, String orderField, String orderType, String report, String isPublic, Nullable`1 workspaceId, String filterString, String period, Nullable`1&amp; resultCount) in d:\eResults\16R101\Glintths.Er.WebServices\Data\Glintths.Er.Common.Data\BusinessEntities\Documents\Document\DocumentManagementBER.cs:line 602</StackTrace>
  <additionalInfo>
    <info name="MachineName" value="RPEREIRA" />
    <info name="TimeStamp" value="13/04/2016 09:18:22" />
    <info name="FullName" value="Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=4.1.0.0, Culture=neutral, PublicKeyToken=null" />
    <info name="AppDomainName" value="/LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-7-131050113937592137" />
    <info name="ThreadIdentity" value="" />
    <info name="WindowsIdentity" value="NT AUTHORITY\SYSTEM" />
  </additionalInfo>
</Exception>
Category: General
Priority: 0
EventId: 100
Severity: Error
Title:Enterprise Library Exception Handling
Machine: RPEREIRA
Application Domain: /LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-7-131050113937592137
Process Id: 13368
Process Name: C:\WINDOWS\SysWOW64\inetsrv\w3wp.exe
Win32 Thread Id: 10384
Thread Name: 
Extended Properties: 
----------------------------------------
----------------------------------------
Timestamp: 13/04/2016 09:22:21
Message: <Exception handlingInstanceId="51262279-fb7f-43fa-a75b-dce022f79187">
  <Description>An exception of type 'Oracle.DataAccess.Client.OracleException' occurred and was caught.</Description>
  <DateTime>2016-04-13 10:22:21Z</DateTime>
  <ExceptionType>Oracle.DataAccess.Client.OracleException, Oracle.DataAccess, Version=2.112.3.0, Culture=neutral, PublicKeyToken=89b483f429c47342</ExceptionType>
  <Message>ORA-20005: CONTEXTO DE ACESSO INVALIDO
ORA-06512: at "ERESULTS_V2_16R101.PCK_ER_DOCS", line 311
ORA-06512: at "ERESULTS_V2_16R101.PCK_ER_DOCS", line 2431
ORA-06512: at line 1</Message>
  <Source>Oracle Data Provider for .NET</Source>
  <HelpLink />
  <Property name="Errors">Oracle.DataAccess.Client.OracleErrorCollection</Property>
  <Property name="DataSource">HSDEV</Property>
  <Property name="Procedure">PCK_ER_DOCS.GetDocumentsByMultiCriteria</Property>
  <Property name="Number">20005</Property>
  <Property name="ErrorCode">-2147467259</Property>
  <Property name="Data">System.Collections.ListDictionaryInternal</Property>
  <Property name="TargetSite">Void HandleErrorHelper(Int32, Oracle.DataAccess.Client.OracleConnection, IntPtr, Oracle.DataAccess.Client.OpoSqlValCtx*, System.Object, System.String, Boolean)</Property>
  <Property name="HResult">-2147467259</Property>
  <StackTrace>   at Oracle.DataAccess.Client.OracleException.HandleErrorHelper(Int32 errCode, OracleConnection conn, IntPtr opsErrCtx, OpoSqlValCtx* pOpoSqlValCtx, Object src, String procedure, Boolean bCheck)
   at Oracle.DataAccess.Client.OracleException.HandleError(Int32 errCode, OracleConnection conn, String procedure, IntPtr opsErrCtx, OpoSqlValCtx* pOpoSqlValCtx, Object src, Boolean bCheck)
   at Oracle.DataAccess.Client.OracleCommand.ExecuteReader(Boolean requery, Boolean fillRequest, CommandBehavior behavior)
   at Oracle.DataAccess.Client.OracleCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.DoExecuteReader(DbCommand command, CommandBehavior cmdBehavior)
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.ExecuteReader(DbCommand command)
   at EntLibContrib.Data.OdpNet.OracleDatabase.ExecuteReader(DbCommand command)
   at Cpchs.Eresults.Common.WCF.BusinessEntities.DocumentManagementBER.GetDocsDB(String companyDB, String documentRef, String documentExternalId, String entitiesIds, String episodeType, String episodeId, String patientId, String patientType, Nullable`1 episodeStartDate, Nullable`1 episodeEndDate, String institution, String place, String application, String documentType, Nullable`1 executionStartDate, Nullable`1 executionEndDate, Nullable`1 validationStartDate, Nullable`1 validationEndDate, Nullable`1 emissionStartDate, Nullable`1 emissionEndDate, String reqService, String execService, String globalFilters, String docsSession, String servsSession, String username, Nullable`1 pageNumber, Nullable`1 itemsPerPage, String orderField, String orderType, String report, String isPublic, Nullable`1 workspaceId, String filterString, String period, Nullable`1&amp; resultCount) in d:\eResults\16R101\Glintths.Er.WebServices\Data\Glintths.Er.Common.Data\BusinessEntities\Documents\Document\DocumentManagementBER.cs:line 602</StackTrace>
  <additionalInfo>
    <info name="MachineName" value="RPEREIRA" />
    <info name="TimeStamp" value="13/04/2016 09:22:21" />
    <info name="FullName" value="Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=4.1.0.0, Culture=neutral, PublicKeyToken=null" />
    <info name="AppDomainName" value="/LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-7-131050113937592137" />
    <info name="ThreadIdentity" value="" />
    <info name="WindowsIdentity" value="NT AUTHORITY\SYSTEM" />
  </additionalInfo>
</Exception>
Category: General
Priority: 0
EventId: 100
Severity: Error
Title:Enterprise Library Exception Handling
Machine: RPEREIRA
Application Domain: /LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-7-131050113937592137
Process Id: 13368
Process Name: C:\WINDOWS\SysWOW64\inetsrv\w3wp.exe
Win32 Thread Id: 12128
Thread Name: 
Extended Properties: 
----------------------------------------
----------------------------------------
Timestamp: 13/04/2016 09:25:34
Message: <Exception handlingInstanceId="388e85e9-a680-41b9-9175-30ca6e8578f6">
  <Description>An exception of type 'Oracle.DataAccess.Client.OracleException' occurred and was caught.</Description>
  <DateTime>2016-04-13 10:25:34Z</DateTime>
  <ExceptionType>Oracle.DataAccess.Client.OracleException, Oracle.DataAccess, Version=2.112.3.0, Culture=neutral, PublicKeyToken=89b483f429c47342</ExceptionType>
  <Message>ORA-20005: CONTEXTO DE ACESSO INVALIDO
ORA-06512: at "ERESULTS_V2_16R101.PCK_ER_DOCS", line 311
ORA-06512: at "ERESULTS_V2_16R101.PCK_ER_DOCS", line 2431
ORA-06512: at line 1</Message>
  <Source>Oracle Data Provider for .NET</Source>
  <HelpLink />
  <Property name="Errors">Oracle.DataAccess.Client.OracleErrorCollection</Property>
  <Property name="DataSource">HSDEV</Property>
  <Property name="Procedure">PCK_ER_DOCS.GetDocumentsByMultiCriteria</Property>
  <Property name="Number">20005</Property>
  <Property name="ErrorCode">-2147467259</Property>
  <Property name="Data">System.Collections.ListDictionaryInternal</Property>
  <Property name="TargetSite">Void HandleErrorHelper(Int32, Oracle.DataAccess.Client.OracleConnection, IntPtr, Oracle.DataAccess.Client.OpoSqlValCtx*, System.Object, System.String, Boolean)</Property>
  <Property name="HResult">-2147467259</Property>
  <StackTrace>   at Oracle.DataAccess.Client.OracleException.HandleErrorHelper(Int32 errCode, OracleConnection conn, IntPtr opsErrCtx, OpoSqlValCtx* pOpoSqlValCtx, Object src, String procedure, Boolean bCheck)
   at Oracle.DataAccess.Client.OracleException.HandleError(Int32 errCode, OracleConnection conn, String procedure, IntPtr opsErrCtx, OpoSqlValCtx* pOpoSqlValCtx, Object src, Boolean bCheck)
   at Oracle.DataAccess.Client.OracleCommand.ExecuteReader(Boolean requery, Boolean fillRequest, CommandBehavior behavior)
   at Oracle.DataAccess.Client.OracleCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.DoExecuteReader(DbCommand command, CommandBehavior cmdBehavior)
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.ExecuteReader(DbCommand command)
   at EntLibContrib.Data.OdpNet.OracleDatabase.ExecuteReader(DbCommand command)
   at Cpchs.Eresults.Common.WCF.BusinessEntities.DocumentManagementBER.GetDocsDB(String companyDB, String documentRef, String documentExternalId, String entitiesIds, String episodeType, String episodeId, String patientId, String patientType, Nullable`1 episodeStartDate, Nullable`1 episodeEndDate, String institution, String place, String application, String documentType, Nullable`1 executionStartDate, Nullable`1 executionEndDate, Nullable`1 validationStartDate, Nullable`1 validationEndDate, Nullable`1 emissionStartDate, Nullable`1 emissionEndDate, String reqService, String execService, String globalFilters, String docsSession, String servsSession, String username, Nullable`1 pageNumber, Nullable`1 itemsPerPage, String orderField, String orderType, String report, String isPublic, Nullable`1 workspaceId, String filterString, String period, Nullable`1&amp; resultCount) in d:\eResults\16R101\Glintths.Er.WebServices\Data\Glintths.Er.Common.Data\BusinessEntities\Documents\Document\DocumentManagementBER.cs:line 602</StackTrace>
  <additionalInfo>
    <info name="MachineName" value="RPEREIRA" />
    <info name="TimeStamp" value="13/04/2016 09:25:34" />
    <info name="FullName" value="Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=4.1.0.0, Culture=neutral, PublicKeyToken=null" />
    <info name="AppDomainName" value="/LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-7-131050113937592137" />
    <info name="ThreadIdentity" value="" />
    <info name="WindowsIdentity" value="NT AUTHORITY\SYSTEM" />
  </additionalInfo>
</Exception>
Category: General
Priority: 0
EventId: 100
Severity: Error
Title:Enterprise Library Exception Handling
Machine: RPEREIRA
Application Domain: /LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-7-131050113937592137
Process Id: 13368
Process Name: C:\WINDOWS\SysWOW64\inetsrv\w3wp.exe
Win32 Thread Id: 14440
Thread Name: 
Extended Properties: 
----------------------------------------
----------------------------------------
Timestamp: 03/05/2016 14:20:13
Message: <Exception handlingInstanceId="094c6260-0b5c-457b-af12-1ebfc1b0adc0">
  <Description>An exception of type 'Oracle.DataAccess.Client.OracleException' occurred and was caught.</Description>
  <DateTime>2016-05-03 15:20:13Z</DateTime>
  <ExceptionType>Oracle.DataAccess.Client.OracleException, Oracle.DataAccess, Version=2.112.3.0, Culture=neutral, PublicKeyToken=89b483f429c47342</ExceptionType>
  <Message>ORA-20005: CONTEXTO DE ACESSO INVALIDO
ORA-06512: at "ERESULTS_V2_16R101.PCK_ER_DOCS", line 314
ORA-06512: at "ERESULTS_V2_16R101.PCK_ER_DOCS", line 2443
ORA-06512: at line 1</Message>
  <Source>Oracle Data Provider for .NET</Source>
  <HelpLink />
  <Property name="Errors">Oracle.DataAccess.Client.OracleErrorCollection</Property>
  <Property name="DataSource">HSDEV</Property>
  <Property name="Procedure">PCK_ER_DOCS.GetDocumentsByMultiCriteria</Property>
  <Property name="Number">20005</Property>
  <Property name="ErrorCode">-2147467259</Property>
  <Property name="Data">System.Collections.ListDictionaryInternal</Property>
  <Property name="TargetSite">Void HandleErrorHelper(Int32, Oracle.DataAccess.Client.OracleConnection, IntPtr, Oracle.DataAccess.Client.OpoSqlValCtx*, System.Object, System.String, Boolean)</Property>
  <Property name="HResult">-2147467259</Property>
  <StackTrace>   at Oracle.DataAccess.Client.OracleException.HandleErrorHelper(Int32 errCode, OracleConnection conn, IntPtr opsErrCtx, OpoSqlValCtx* pOpoSqlValCtx, Object src, String procedure, Boolean bCheck)
   at Oracle.DataAccess.Client.OracleException.HandleError(Int32 errCode, OracleConnection conn, String procedure, IntPtr opsErrCtx, OpoSqlValCtx* pOpoSqlValCtx, Object src, Boolean bCheck)
   at Oracle.DataAccess.Client.OracleCommand.ExecuteReader(Boolean requery, Boolean fillRequest, CommandBehavior behavior)
   at Oracle.DataAccess.Client.OracleCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.DoExecuteReader(DbCommand command, CommandBehavior cmdBehavior)
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.ExecuteReader(DbCommand command)
   at EntLibContrib.Data.OdpNet.OracleDatabase.ExecuteReader(DbCommand command)
   at Cpchs.Eresults.Common.WCF.BusinessEntities.DocumentManagementBER.GetDocsDB(String companyDB, String documentRef, String documentExternalId, String entitiesIds, String episodeType, String episodeId, String patientId, String patientType, Nullable`1 episodeStartDate, Nullable`1 episodeEndDate, String institution, String place, String application, String documentType, Nullable`1 executionStartDate, Nullable`1 executionEndDate, Nullable`1 validationStartDate, Nullable`1 validationEndDate, Nullable`1 emissionStartDate, Nullable`1 emissionEndDate, String reqService, String execService, String globalFilters, String docsSession, String servsSession, String username, Nullable`1 pageNumber, Nullable`1 itemsPerPage, String orderField, String orderType, String report, String isPublic, Nullable`1 workspaceId, String filterString, String period, Nullable`1&amp; resultCount) in d:\eResults\16R101\Glintths.Er.WebServices\Data\Glintths.Er.Common.Data\BusinessEntities\Documents\Document\DocumentManagementBER.cs:line 602</StackTrace>
  <additionalInfo>
    <info name="MachineName" value="RPEREIRA" />
    <info name="TimeStamp" value="03/05/2016 14:20:13" />
    <info name="FullName" value="Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=4.1.0.0, Culture=neutral, PublicKeyToken=null" />
    <info name="AppDomainName" value="/LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-8-131067522503768561" />
    <info name="ThreadIdentity" value="" />
    <info name="WindowsIdentity" value="NT AUTHORITY\SYSTEM" />
  </additionalInfo>
</Exception>
Category: General
Priority: 0
EventId: 100
Severity: Error
Title:Enterprise Library Exception Handling
Machine: RPEREIRA
Application Domain: /LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-8-131067522503768561
Process Id: 19320
Process Name: C:\WINDOWS\SysWOW64\inetsrv\w3wp.exe
Win32 Thread Id: 21500
Thread Name: 
Extended Properties: 
----------------------------------------
----------------------------------------
Timestamp: 04/05/2016 14:06:01
Message: <Exception handlingInstanceId="e7752917-e649-45af-a54e-698c8e2212b6">
  <Description>An exception of type 'Oracle.DataAccess.Client.OracleException' occurred and was caught.</Description>
  <DateTime>2016-05-04 15:06:01Z</DateTime>
  <ExceptionType>Oracle.DataAccess.Client.OracleException, Oracle.DataAccess, Version=2.112.3.0, Culture=neutral, PublicKeyToken=89b483f429c47342</ExceptionType>
  <Message>ORA-20005: CONTEXTO DE ACESSO INVALIDO
ORA-06512: at "ERESULTS_V2_16R101.PCK_ER_DOCS", line 314
ORA-06512: at "ERESULTS_V2_16R101.PCK_ER_DOCS", line 2443
ORA-06512: at line 1</Message>
  <Source>Oracle Data Provider for .NET</Source>
  <HelpLink />
  <Property name="Errors">Oracle.DataAccess.Client.OracleErrorCollection</Property>
  <Property name="DataSource">HSDEV</Property>
  <Property name="Procedure">PCK_ER_DOCS.GetDocumentsByMultiCriteria</Property>
  <Property name="Number">20005</Property>
  <Property name="ErrorCode">-2147467259</Property>
  <Property name="Data">System.Collections.ListDictionaryInternal</Property>
  <Property name="TargetSite">Void HandleErrorHelper(Int32, Oracle.DataAccess.Client.OracleConnection, IntPtr, Oracle.DataAccess.Client.OpoSqlValCtx*, System.Object, System.String, Boolean)</Property>
  <Property name="HResult">-2147467259</Property>
  <StackTrace>   at Oracle.DataAccess.Client.OracleException.HandleErrorHelper(Int32 errCode, OracleConnection conn, IntPtr opsErrCtx, OpoSqlValCtx* pOpoSqlValCtx, Object src, String procedure, Boolean bCheck)
   at Oracle.DataAccess.Client.OracleException.HandleError(Int32 errCode, OracleConnection conn, String procedure, IntPtr opsErrCtx, OpoSqlValCtx* pOpoSqlValCtx, Object src, Boolean bCheck)
   at Oracle.DataAccess.Client.OracleCommand.ExecuteReader(Boolean requery, Boolean fillRequest, CommandBehavior behavior)
   at Oracle.DataAccess.Client.OracleCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.DoExecuteReader(DbCommand command, CommandBehavior cmdBehavior)
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.ExecuteReader(DbCommand command)
   at EntLibContrib.Data.OdpNet.OracleDatabase.ExecuteReader(DbCommand command)
   at Cpchs.Eresults.Common.WCF.BusinessEntities.DocumentManagementBER.GetDocsDB(String companyDB, String documentRef, String documentExternalId, String entitiesIds, String episodeType, String episodeId, String patientId, String patientType, Nullable`1 episodeStartDate, Nullable`1 episodeEndDate, String institution, String place, String application, String documentType, Nullable`1 executionStartDate, Nullable`1 executionEndDate, Nullable`1 validationStartDate, Nullable`1 validationEndDate, Nullable`1 emissionStartDate, Nullable`1 emissionEndDate, String reqService, String execService, String globalFilters, String docsSession, String servsSession, String username, Nullable`1 pageNumber, Nullable`1 itemsPerPage, String orderField, String orderType, String report, String isPublic, Nullable`1 workspaceId, String filterString, String period, Nullable`1&amp; resultCount) in d:\eResults\16R101\Glintths.Er.WebServices\Data\Glintths.Er.Common.Data\BusinessEntities\Documents\Document\DocumentManagementBER.cs:line 602</StackTrace>
  <additionalInfo>
    <info name="MachineName" value="RPEREIRA" />
    <info name="TimeStamp" value="04/05/2016 14:06:01" />
    <info name="FullName" value="Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=4.1.0.0, Culture=neutral, PublicKeyToken=null" />
    <info name="AppDomainName" value="/LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-7-131068443597029007" />
    <info name="ThreadIdentity" value="" />
    <info name="WindowsIdentity" value="NT AUTHORITY\SYSTEM" />
  </additionalInfo>
</Exception>
Category: General
Priority: 0
EventId: 100
Severity: Error
Title:Enterprise Library Exception Handling
Machine: RPEREIRA
Application Domain: /LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-7-131068443597029007
Process Id: 34620
Process Name: C:\WINDOWS\SysWOW64\inetsrv\w3wp.exe
Win32 Thread Id: 26340
Thread Name: 
Extended Properties: 
----------------------------------------
----------------------------------------
Timestamp: 04/05/2016 14:07:23
Message: <Exception handlingInstanceId="8b4bbe61-4464-4b4e-9f3f-73e6edc0f304">
  <Description>An exception of type 'Oracle.DataAccess.Client.OracleException' occurred and was caught.</Description>
  <DateTime>2016-05-04 15:07:23Z</DateTime>
  <ExceptionType>Oracle.DataAccess.Client.OracleException, Oracle.DataAccess, Version=2.112.3.0, Culture=neutral, PublicKeyToken=89b483f429c47342</ExceptionType>
  <Message>ORA-20005: CONTEXTO DE ACESSO INVALIDO
ORA-06512: at "ERESULTS_V2_16R101.PCK_ER_DOCS", line 314
ORA-06512: at "ERESULTS_V2_16R101.PCK_ER_DOCS", line 2443
ORA-06512: at line 1</Message>
  <Source>Oracle Data Provider for .NET</Source>
  <HelpLink />
  <Property name="Errors">Oracle.DataAccess.Client.OracleErrorCollection</Property>
  <Property name="DataSource">HSDEV</Property>
  <Property name="Procedure">PCK_ER_DOCS.GetDocumentsByMultiCriteria</Property>
  <Property name="Number">20005</Property>
  <Property name="ErrorCode">-2147467259</Property>
  <Property name="Data">System.Collections.ListDictionaryInternal</Property>
  <Property name="TargetSite">Void HandleErrorHelper(Int32, Oracle.DataAccess.Client.OracleConnection, IntPtr, Oracle.DataAccess.Client.OpoSqlValCtx*, System.Object, System.String, Boolean)</Property>
  <Property name="HResult">-2147467259</Property>
  <StackTrace>   at Oracle.DataAccess.Client.OracleException.HandleErrorHelper(Int32 errCode, OracleConnection conn, IntPtr opsErrCtx, OpoSqlValCtx* pOpoSqlValCtx, Object src, String procedure, Boolean bCheck)
   at Oracle.DataAccess.Client.OracleException.HandleError(Int32 errCode, OracleConnection conn, String procedure, IntPtr opsErrCtx, OpoSqlValCtx* pOpoSqlValCtx, Object src, Boolean bCheck)
   at Oracle.DataAccess.Client.OracleCommand.ExecuteReader(Boolean requery, Boolean fillRequest, CommandBehavior behavior)
   at Oracle.DataAccess.Client.OracleCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.DoExecuteReader(DbCommand command, CommandBehavior cmdBehavior)
   at Microsoft.Practices.EnterpriseLibrary.Data.Database.ExecuteReader(DbCommand command)
   at EntLibContrib.Data.OdpNet.OracleDatabase.ExecuteReader(DbCommand command)
   at Cpchs.Eresults.Common.WCF.BusinessEntities.DocumentManagementBER.GetDocsDB(String companyDB, String documentRef, String documentExternalId, String entitiesIds, String episodeType, String episodeId, String patientId, String patientType, Nullable`1 episodeStartDate, Nullable`1 episodeEndDate, String institution, String place, String application, String documentType, Nullable`1 executionStartDate, Nullable`1 executionEndDate, Nullable`1 validationStartDate, Nullable`1 validationEndDate, Nullable`1 emissionStartDate, Nullable`1 emissionEndDate, String reqService, String execService, String globalFilters, String docsSession, String servsSession, String username, Nullable`1 pageNumber, Nullable`1 itemsPerPage, String orderField, String orderType, String report, String isPublic, Nullable`1 workspaceId, String filterString, String period, Nullable`1&amp; resultCount) in d:\eResults\16R101\Glintths.Er.WebServices\Data\Glintths.Er.Common.Data\BusinessEntities\Documents\Document\DocumentManagementBER.cs:line 602</StackTrace>
  <additionalInfo>
    <info name="MachineName" value="RPEREIRA" />
    <info name="TimeStamp" value="04/05/2016 14:07:23" />
    <info name="FullName" value="Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=4.1.0.0, Culture=neutral, PublicKeyToken=null" />
    <info name="AppDomainName" value="/LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-7-131068443597029007" />
    <info name="ThreadIdentity" value="" />
    <info name="WindowsIdentity" value="NT AUTHORITY\SYSTEM" />
  </additionalInfo>
</Exception>
Category: General
Priority: 0
EventId: 100
Severity: Error
Title:Enterprise Library Exception Handling
Machine: RPEREIRA
Application Domain: /LM/W3SVC/3999980001/ROOT/Cpchs.Documents.WCF.Host-7-131068443597029007
Process Id: 34620
Process Name: C:\WINDOWS\SysWOW64\inetsrv\w3wp.exe
Win32 Thread Id: 31180
Thread Name: 
Extended Properties: 
----------------------------------------
